/*
Navicat PGSQL Data Transfer

Source Server         : remote postgresql_copy
Source Server Version : 90409
Source Host           : remote
Source Database       : remotedatabase
Source Schema         : public

Target Server Type    : PGSQL
Target Server Version : 90409
File Encoding         : 65001

Date: 2016-10-15 08:48:51
*/


-- ----------------------------
-- Table structure for palabras
-- ----------------------------
DROP TABLE IF EXISTS "public"."palabras";
CREATE TABLE "public"."palabras" (
"ing" varchar COLLATE "default",
"esp" varchar COLLATE "default",
"prt" varchar COLLATE "default",
"n" numeric,
"id" int4 DEFAULT nextval('palabras_id_seq1'::regclass) NOT NULL,
"imgurl" varchar COLLATE "default"
)
WITH (OIDS=FALSE)

;

-- ----------------------------
-- Records of palabras
-- ----------------------------
INSERT INTO "public"."palabras" VALUES ('act', 'acto', 'ato', '1', '1', null);
INSERT INTO "public"."palabras" VALUES ('admit', 'admitir', 'admitir', '1', '2', null);
INSERT INTO "public"."palabras" VALUES ('air', 'aire', 'ar', '1', '3', null);
INSERT INTO "public"."palabras" VALUES ('already', 'ya', 'já', '1', '4', null);
INSERT INTO "public"."palabras" VALUES ('animal', 'animal', 'animal', '1', '5', null);
INSERT INTO "public"."palabras" VALUES ('apple', 'manzana', 'maçã', '1', '6', null);
INSERT INTO "public"."palabras" VALUES ('are', 'somos o estamos', 'são', '1', '7', null);
INSERT INTO "public"."palabras" VALUES ('army', 'ejercito', 'exército', '1', '8', null);
INSERT INTO "public"."palabras" VALUES ('article', 'articulo', 'artigo', '1', '9', null);
INSERT INTO "public"."palabras" VALUES ('baby', 'bebe', 'bebê', '1', '10', 'http://i.giphy.com/xbkMY5GeLGZG0.gif');
INSERT INTO "public"."palabras" VALUES ('bad', 'malo', 'mau', '1', '11', null);
INSERT INTO "public"."palabras" VALUES ('ball', 'bola', 'bola', '1', '12', null);
INSERT INTO "public"."palabras" VALUES ('band', 'banda', 'banda', '1', '13', null);
INSERT INTO "public"."palabras" VALUES ('basket', 'canasta', 'cesta', '1', '14', null);
INSERT INTO "public"."palabras" VALUES ('battle', 'batalla', 'batalha', '1', '15', null);
INSERT INTO "public"."palabras" VALUES ('be', 'ser o estar', 'estar', '1', '16', null);
INSERT INTO "public"."palabras" VALUES ('beauty', 'belleza', 'beleza', '1', '17', null);
INSERT INTO "public"."palabras" VALUES ('bed', 'cama', 'cama', '1', '18', null);
INSERT INTO "public"."palabras" VALUES ('before', 'antes', 'antes', '1', '19', null);
INSERT INTO "public"."palabras" VALUES ('begin', 'empezar', 'início', '1', '20', 'http://i.giphy.com/xNBcChLQt7s9a.gif');
INSERT INTO "public"."palabras" VALUES ('bell', 'campana', 'Sino', '1', '21', null);
INSERT INTO "public"."palabras" VALUES ('better', 'mejor', 'melhor', '1', '22', null);
INSERT INTO "public"."palabras" VALUES ('bird', 'pájaro', 'pássaro', '1', '23', null);
INSERT INTO "public"."palabras" VALUES ('blood', 'sangre', 'sangue', '1', '24', null);
INSERT INTO "public"."palabras" VALUES ('blue', 'azul', 'azul', '1', '25', null);
INSERT INTO "public"."palabras" VALUES ('book', 'libro', 'livro', '1', '26', null);
INSERT INTO "public"."palabras" VALUES ('box', 'caja', 'caixa', '1', '27', null);
INSERT INTO "public"."palabras" VALUES ('boy', 'muchacho', 'Garoto', '1', '28', null);
INSERT INTO "public"."palabras" VALUES ('brother', 'hermano', 'irmão', '1', '29', null);
INSERT INTO "public"."palabras" VALUES ('business', 'negocio', 'negócio', '1', '30', 'http://i.giphy.com/yoJC2GnSClbPOkV0eA.gif');
INSERT INTO "public"."palabras" VALUES ('by', 'por', 'de', '1', '31', null);
INSERT INTO "public"."palabras" VALUES ('captain', 'capitán', 'capitão', '1', '32', null);
INSERT INTO "public"."palabras" VALUES ('car', 'carro', 'carro', '1', '33', null);
INSERT INTO "public"."palabras" VALUES ('cent', 'centavo', 'centavo', '1', '34', null);
INSERT INTO "public"."palabras" VALUES ('certain', 'certeza', 'certo', '1', '35', null);
INSERT INTO "public"."palabras" VALUES ('color', 'color', 'cor', '1', '36', null);
INSERT INTO "public"."palabras" VALUES ('command', 'comandar', 'comando', '1', '37', null);
INSERT INTO "public"."palabras" VALUES ('company', 'compañía', 'companhia', '1', '38', null);
INSERT INTO "public"."palabras" VALUES ('complete', 'completar', 'completo', '1', '39', null);
INSERT INTO "public"."palabras" VALUES ('condition', 'condición', 'condição', '1', '40', 'http://i.giphy.com/TEFplLVRDMWBi.gif');
INSERT INTO "public"."palabras" VALUES ('consider', 'considerar', 'considerar', '1', '41', null);
INSERT INTO "public"."palabras" VALUES ('continue', 'continuar', 'continuar', '1', '42', null);
INSERT INTO "public"."palabras" VALUES ('control', 'control', 'controle', '1', '43', null);
INSERT INTO "public"."palabras" VALUES ('course', 'curso', 'curso', '1', '44', null);
INSERT INTO "public"."palabras" VALUES ('cross', 'cruzar', 'Cruz', '1', '45', null);
INSERT INTO "public"."palabras" VALUES ('dance', 'danzar', 'dança', '1', '46', null);
INSERT INTO "public"."palabras" VALUES ('date', 'fecha', 'data', '1', '47', null);
INSERT INTO "public"."palabras" VALUES ('decide', 'decidir', 'decidir', '1', '48', null);
INSERT INTO "public"."palabras" VALUES ('declare', 'declarar', 'declarar', '1', '49', null);
INSERT INTO "public"."palabras" VALUES ('demand', 'demandar', 'exigem', '1', '50', 'http://i.giphy.com/11sBLVxNs7v6WA.gif');
INSERT INTO "public"."palabras" VALUES ('different', 'diferente', 'diferente', '1', '51', null);
INSERT INTO "public"."palabras" VALUES ('direct', 'directo', 'direto', '1', '52', null);
INSERT INTO "public"."palabras" VALUES ('distant', 'distante', 'distante', '1', '53', null);
INSERT INTO "public"."palabras" VALUES ('divide', 'dividir', 'dividir', '1', '54', null);
INSERT INTO "public"."palabras" VALUES ('doctor', 'doctor', 'médico', '1', '55', null);
INSERT INTO "public"."palabras" VALUES ('dog', 'perro', 'cachorro', '1', '56', null);
INSERT INTO "public"."palabras" VALUES ('dollar', 'dólar', 'dólar', '1', '57', null);
INSERT INTO "public"."palabras" VALUES ('door', 'puerta', 'porta', '1', '58', null);
INSERT INTO "public"."palabras" VALUES ('double', 'doble', 'duplo', '1', '59', null);
INSERT INTO "public"."palabras" VALUES ('electric', 'eléctrico', 'elétrico', '1', '60', 'http://i.giphy.com/7TM8kWy04HzcA.gif');
INSERT INTO "public"."palabras" VALUES ('enemy', 'enemigo', 'inimigo', '1', '61', null);
INSERT INTO "public"."palabras" VALUES ('escape', 'escapar', 'escapar', '1', '62', null);
INSERT INTO "public"."palabras" VALUES ('especially', 'especialmente', 'especialmente', '1', '63', null);
INSERT INTO "public"."palabras" VALUES ('experience', 'experiencia', 'experiência', '1', '64', null);
INSERT INTO "public"."palabras" VALUES ('express', 'expreso', 'expressar', '1', '65', null);
INSERT INTO "public"."palabras" VALUES ('family', 'familia', 'família', '1', '66', null);
INSERT INTO "public"."palabras" VALUES ('father', 'padre', 'pai', '1', '67', null);
INSERT INTO "public"."palabras" VALUES ('favor', 'favor', 'favor', '1', '68', null);
INSERT INTO "public"."palabras" VALUES ('food', 'comida', 'comida', '1', '69', null);
INSERT INTO "public"."palabras" VALUES ('foot', 'pie', 'pé', '1', '70', 'http://i.giphy.com/xTiTnyijMsXgn6Bzzy.gif');
INSERT INTO "public"."palabras" VALUES ('first', 'primero', 'primeiro', '1', '71', null);
INSERT INTO "public"."palabras" VALUES ('finish', 'finalizar', 'terminar', '1', '72', null);
INSERT INTO "public"."palabras" VALUES ('future', 'futuro', 'futuro', '1', '73', null);
INSERT INTO "public"."palabras" VALUES ('best', 'mejor', 'melhor', '1', '74', null);
INSERT INTO "public"."palabras" VALUES ('body', 'cuerpo', 'corpo', '1', '75', null);
INSERT INTO "public"."palabras" VALUES ('good', 'bueno', 'boa', '1', '76', null);
INSERT INTO "public"."palabras" VALUES ('today', 'hoy', 'hoje', '1', '77', null);
INSERT INTO "public"."palabras" VALUES ('chance', 'chance', 'chance', '1', '78', null);
INSERT INTO "public"."palabras" VALUES ('character', 'carácter', 'personagem', '1', '79', null);
INSERT INTO "public"."palabras" VALUES ('children', 'niño', 'criança', '1', '80', 'http://i.giphy.com/NENKWiQoPJqo.gif');
INSERT INTO "public"."palabras" VALUES ('circle', 'circulo', 'círculo', '1', '81', null);
INSERT INTO "public"."palabras" VALUES ('class', 'clase', 'classe', '1', '82', null);
INSERT INTO "public"."palabras" VALUES ('clock', 'reloj', 'relógio', '1', '83', null);
INSERT INTO "public"."palabras" VALUES ('college', 'colegio', 'faculdade', '1', '84', null);
INSERT INTO "public"."palabras" VALUES ('for', 'para', 'para', '1', '85', null);
INSERT INTO "public"."palabras" VALUES ('form', 'forma', 'formato', '1', '86', null);
INSERT INTO "public"."palabras" VALUES ('force', 'fuerza', 'força', '1', '87', null);
INSERT INTO "public"."palabras" VALUES ('free', 'libre', 'livre', '1', '88', null);
INSERT INTO "public"."palabras" VALUES ('friend', 'amigo', 'amigo', '1', '89', null);
INSERT INTO "public"."palabras" VALUES ('from', 'desde', 'a partir de', '1', '90', 'http://i.giphy.com/10UeedrT5MIfPG.gif');
INSERT INTO "public"."palabras" VALUES ('front', 'frente', 'frente', '1', '91', null);
INSERT INTO "public"."palabras" VALUES ('fruit', 'fruta', 'fruta', '1', '92', null);
INSERT INTO "public"."palabras" VALUES ('game', 'juego', 'jogo', '1', '93', null);
INSERT INTO "public"."palabras" VALUES ('garden', 'jardín', 'jardim', '1', '94', null);
INSERT INTO "public"."palabras" VALUES ('general', 'general', 'geral', '1', '95', null);
INSERT INTO "public"."palabras" VALUES ('gentleman', 'caballero', 'cavalheiro', '1', '96', null);
INSERT INTO "public"."palabras" VALUES ('girl', 'niña', 'menina', '1', '97', null);
INSERT INTO "public"."palabras" VALUES ('glass', 'vidrio, vaso', 'vidro', '1', '98', null);
INSERT INTO "public"."palabras" VALUES ('good bye', 'adiós', 'Tchau', '1', '99', null);
INSERT INTO "public"."palabras" VALUES ('govern', 'gobernar', 'governo', '1', '100', 'http://i.giphy.com/xT5LMHxhOfscxPfIfm.gif');
INSERT INTO "public"."palabras" VALUES ('great', 'estupendo', 'ótimo', '1', '101', null);
INSERT INTO "public"."palabras" VALUES ('group', 'grupo', 'grupo', '1', '102', null);
INSERT INTO "public"."palabras" VALUES ('guard', 'guardia', 'guarda', '1', '103', null);
INSERT INTO "public"."palabras" VALUES ('half', 'mitad', 'metade', '1', '104', null);
INSERT INTO "public"."palabras" VALUES ('hall', 'sala', 'corredor', '1', '105', null);
INSERT INTO "public"."palabras" VALUES ('hand', 'mano', 'mão', '1', '106', null);
INSERT INTO "public"."palabras" VALUES ('happy', 'feliz', 'feliz', '1', '107', null);
INSERT INTO "public"."palabras" VALUES ('hello', 'hola', 'Olá', '1', '108', null);
INSERT INTO "public"."palabras" VALUES ('history', 'historia', 'história', '1', '109', null);
INSERT INTO "public"."palabras" VALUES ('home', 'casa', 'casa', '1', '110', 'http://i.giphy.com/6HOkD1pSCne4E.gif');
INSERT INTO "public"."palabras" VALUES ('honor', 'honor', 'honra', '1', '111', null);
INSERT INTO "public"."palabras" VALUES ('hour', 'hora', 'hora', '1', '112', null);
INSERT INTO "public"."palabras" VALUES ('human', 'humano', 'humano', '1', '113', null);
INSERT INTO "public"."palabras" VALUES ('I', 'yo', 'eu', '1', '114', null);
INSERT INTO "public"."palabras" VALUES ('idea', 'idea', 'ideia', '1', '115', null);
INSERT INTO "public"."palabras" VALUES ('important', 'importante', 'importante', '1', '116', null);
INSERT INTO "public"."palabras" VALUES ('include', 'incluir', 'incluir', '1', '117', null);
INSERT INTO "public"."palabras" VALUES ('industry', 'industria', 'indústria', '1', '118', null);
INSERT INTO "public"."palabras" VALUES ('interest', 'interés', 'interesse', '1', '119', null);
INSERT INTO "public"."palabras" VALUES ('is', 'es', 'é', '1', '120', 'http://i.giphy.com/daUOBsa1OztxC.gif');
INSERT INTO "public"."palabras" VALUES ('island', 'isla', 'ilha', '1', '121', null);
INSERT INTO "public"."palabras" VALUES ('it', 'esto', 'isto', '1', '122', null);
INSERT INTO "public"."palabras" VALUES ('just', 'justo', 'justo', '1', '123', null);
INSERT INTO "public"."palabras" VALUES ('kiss', 'beso', 'beijo', '1', '124', null);
INSERT INTO "public"."palabras" VALUES ('labor', 'trabajo', 'trabalho', '1', '125', null);
INSERT INTO "public"."palabras" VALUES ('lady', 'dama', 'dama', '1', '126', null);
INSERT INTO "public"."palabras" VALUES ('large', 'largo', 'grande', '1', '127', null);
INSERT INTO "public"."palabras" VALUES ('letter', 'carta', 'carta', '1', '128', null);
INSERT INTO "public"."palabras" VALUES ('little', 'pequeño', 'pequeno', '1', '129', null);
INSERT INTO "public"."palabras" VALUES ('light', 'luz', 'luz', '1', '130', 'http://i.giphy.com/qiMbLh4WHEZyw.gif');
INSERT INTO "public"."palabras" VALUES ('lord', 'señor', 'senhor', '1', '131', null);
INSERT INTO "public"."palabras" VALUES ('long', 'largo', 'longo', '1', '132', null);
INSERT INTO "public"."palabras" VALUES ('love', 'amor', 'amar', '1', '133', null);
INSERT INTO "public"."palabras" VALUES ('machine', 'maquina', 'máquina', '1', '134', null);
INSERT INTO "public"."palabras" VALUES ('made', 'hecho', 'feito', '1', '135', null);
INSERT INTO "public"."palabras" VALUES ('manner', 'manera', 'maneira', '1', '136', null);
INSERT INTO "public"."palabras" VALUES ('market', 'mercado', 'mercado', '1', '137', null);
INSERT INTO "public"."palabras" VALUES ('master', 'maestro', 'dominar', '1', '138', null);
INSERT INTO "public"."palabras" VALUES ('material', 'material', 'material', '1', '139', null);
INSERT INTO "public"."palabras" VALUES ('me', 'yo', 'mim', '1', '140', 'http://i.giphy.com/ftGTY1fO9ARUI.gif');
INSERT INTO "public"."palabras" VALUES ('member', 'miembro', 'membro', '1', '141', null);
INSERT INTO "public"."palabras" VALUES ('men', 'hombre', 'homem', '1', '142', null);
INSERT INTO "public"."palabras" VALUES ('method', 'método', 'método', '1', '143', null);
INSERT INTO "public"."palabras" VALUES ('milk', 'leche', 'leite', '1', '144', null);
INSERT INTO "public"."palabras" VALUES ('million', 'millón', 'milhão', '1', '145', null);
INSERT INTO "public"."palabras" VALUES ('minute', 'minuto', 'minuto', '1', '146', null);
INSERT INTO "public"."palabras" VALUES ('modern', 'moderno', 'moderno', '1', '147', null);
INSERT INTO "public"."palabras" VALUES ('moment', 'momento', 'momento', '1', '148', null);
INSERT INTO "public"."palabras" VALUES ('money', 'dinero', 'dinheiro', '1', '149', null);
INSERT INTO "public"."palabras" VALUES ('more', 'más', 'mais', '1', '150', 'http://i.giphy.com/tbK9kL5uqDQUU.gif');
INSERT INTO "public"."palabras" VALUES ('morning', 'mañana', 'manhã', '1', '151', null);
INSERT INTO "public"."palabras" VALUES ('mother', 'madre', 'mãe', '1', '152', null);
INSERT INTO "public"."palabras" VALUES ('mountain', 'montaña', 'montanha', '1', '153', null);
INSERT INTO "public"."palabras" VALUES ('Mr.', 'señor', 'senhor', '1', '154', null);
INSERT INTO "public"."palabras" VALUES ('Mrs.', 'señora', 'senhora', '1', '155', null);
INSERT INTO "public"."palabras" VALUES ('much', 'mucho', 'muito', '1', '156', null);
INSERT INTO "public"."palabras" VALUES ('music', 'música', 'música', '1', '157', null);
INSERT INTO "public"."palabras" VALUES ('my', 'mío', 'meu', '1', '158', null);
INSERT INTO "public"."palabras" VALUES ('name', 'nombre', 'nome', '1', '159', null);
INSERT INTO "public"."palabras" VALUES ('nation', 'nación', 'nação', '1', '160', 'http://i.giphy.com/xThuWp2hJABbmc20Ew.gif');
INSERT INTO "public"."palabras" VALUES ('necessary', 'necesario', 'necessário', '1', '161', null);
INSERT INTO "public"."palabras" VALUES ('nervous', 'nervioso', 'nervoso', '1', '162', null);
INSERT INTO "public"."palabras" VALUES ('never', 'nunca', 'nunca', '1', '163', null);
INSERT INTO "public"."palabras" VALUES ('new', 'nuevo', 'novo', '1', '164', null);
INSERT INTO "public"."palabras" VALUES ('night', 'noche', 'noite', '1', '165', null);
INSERT INTO "public"."palabras" VALUES ('no', 'no', 'não', '1', '166', null);
INSERT INTO "public"."palabras" VALUES ('note', 'nota', 'Nota', '1', '167', null);
INSERT INTO "public"."palabras" VALUES ('notice', 'noticia', 'aviso', '1', '168', null);
INSERT INTO "public"."palabras" VALUES ('number', 'número', 'número', '1', '169', null);
INSERT INTO "public"."palabras" VALUES ('object', 'objeto', 'objeto', '1', '170', 'https://giphy.com/gifs/G9yZMzJe6pMYw/html5');
INSERT INTO "public"."palabras" VALUES ('ocean', 'océano', 'oceano', '1', '171', null);
INSERT INTO "public"."palabras" VALUES ('off', 'apagado', 'fora', '1', '172', null);
INSERT INTO "public"."palabras" VALUES ('oil', 'petróleo', 'óleo', '1', '173', null);
INSERT INTO "public"."palabras" VALUES ('old', 'viejo', 'velho', '1', '174', null);
INSERT INTO "public"."palabras" VALUES ('on', 'en', 'em', '1', '175', null);
INSERT INTO "public"."palabras" VALUES ('one', 'uno', 'um', '1', '176', null);
INSERT INTO "public"."palabras" VALUES ('open', 'abierto', 'aberto', '1', '177', null);
INSERT INTO "public"."palabras" VALUES ('opinion', 'opinión', 'opinião', '1', '178', null);
INSERT INTO "public"."palabras" VALUES ('out', 'fuera', 'Fora', '1', '179', null);
INSERT INTO "public"."palabras" VALUES ('page', 'pagina', 'página', '1', '180', 'http://i.giphy.com/5GoVLqeAOo6PK.gif');
INSERT INTO "public"."palabras" VALUES ('pain', 'dolor', 'dor', '1', '181', null);
INSERT INTO "public"."palabras" VALUES ('paper', 'papel', 'papel', '1', '182', null);
INSERT INTO "public"."palabras" VALUES ('paint', 'pintura', 'pintura', '1', '183', null);
INSERT INTO "public"."palabras" VALUES ('pay', 'pago', 'pagamento', '1', '184', null);
INSERT INTO "public"."palabras" VALUES ('peace', 'paz', 'paz', '1', '185', null);
INSERT INTO "public"."palabras" VALUES ('period', 'periodo', 'período', '1', '186', null);
INSERT INTO "public"."palabras" VALUES ('person', 'persona', 'pessoa', '1', '187', null);
INSERT INTO "public"."palabras" VALUES ('plan', 'plan', 'plano', '1', '188', null);
INSERT INTO "public"."palabras" VALUES ('plant', 'planta', 'plantar', '1', '189', null);
INSERT INTO "public"."palabras" VALUES ('please', 'por favor', 'por favor', '1', '190', 'http://i.giphy.com/3o7abKdjLVFduQcm3e.gif');
INSERT INTO "public"."palabras" VALUES ('position', 'posición', 'posição', '1', '191', null);
INSERT INTO "public"."palabras" VALUES ('possible', 'posible', 'possível', '1', '192', null);
INSERT INTO "public"."palabras" VALUES ('present', 'presente', 'presente', '1', '193', null);
INSERT INTO "public"."palabras" VALUES ('president', 'presidente', 'presidente', '1', '194', null);
INSERT INTO "public"."palabras" VALUES ('probable', 'probable', 'provável', '1', '195', null);
INSERT INTO "public"."palabras" VALUES ('problem', 'problema', 'problema', '1', '196', null);
INSERT INTO "public"."palabras" VALUES ('promise', 'promesa', 'promessa', '1', '197', null);
INSERT INTO "public"."palabras" VALUES ('public', 'publico', 'público', '1', '198', null);
INSERT INTO "public"."palabras" VALUES ('ready', 'listo', 'pronto', '1', '199', null);
INSERT INTO "public"."palabras" VALUES ('record', 'registro', 'registro', '1', '200', 'http://i.giphy.com/xT0GqGUyFPeYYmYD5K.gif');
INSERT INTO "public"."palabras" VALUES ('remember', 'recuerda', 'lembrar', '1', '201', null);
INSERT INTO "public"."palabras" VALUES ('report', 'reporte', 'relatório', '1', '202', null);
INSERT INTO "public"."palabras" VALUES ('result', 'resultado', 'resultado', '1', '203', null);
INSERT INTO "public"."palabras" VALUES ('room', 'cuarto', 'quarto', '1', '204', null);
INSERT INTO "public"."palabras" VALUES ('safe', 'seguro', 'seguro', '1', '205', null);
INSERT INTO "public"."palabras" VALUES ('scene', 'escena', 'cena', '1', '206', null);
INSERT INTO "public"."palabras" VALUES ('school', 'escuela', 'escola', '1', '207', null);
INSERT INTO "public"."palabras" VALUES ('second', 'segundo', 'segundo', '1', '208', null);
INSERT INTO "public"."palabras" VALUES ('separate', 'separar', 'separar', '1', '209', null);
INSERT INTO "public"."palabras" VALUES ('service', 'servicio', 'serviço', '1', '210', 'http://i.giphy.com/l0MYEqEzwMWFCg8rm.gif');
INSERT INTO "public"."palabras" VALUES ('shoe', 'zapato', 'sapato', '1', '211', null);
INSERT INTO "public"."palabras" VALUES ('simple', 'sencillo', 'simples', '1', '212', null);
INSERT INTO "public"."palabras" VALUES ('sing', 'cantar', 'cantar', '1', '213', null);
INSERT INTO "public"."palabras" VALUES ('sister', 'hermana', 'irmã', '1', '214', null);
INSERT INTO "public"."palabras" VALUES ('size', 'tamaño', 'tamanho', '1', '215', null);
INSERT INTO "public"."palabras" VALUES ('soldier', 'soldado', 'soldado', '1', '216', null);
INSERT INTO "public"."palabras" VALUES ('son', 'hijo', 'filho', '1', '217', null);
INSERT INTO "public"."palabras" VALUES ('space', 'espacio', 'espaço', '1', '218', null);
INSERT INTO "public"."palabras" VALUES ('special', 'especial', 'especial', '1', '219', null);
INSERT INTO "public"."palabras" VALUES ('spirit', 'espíritu', 'espírito', '1', '220', 'http://i.giphy.com/99tK62nC8tb9e.gif');
INSERT INTO "public"."palabras" VALUES ('state', 'estado', 'estado', '1', '221', null);
INSERT INTO "public"."palabras" VALUES ('station', 'estación', 'estação', '1', '222', null);
INSERT INTO "public"."palabras" VALUES ('stop', 'parar', 'Pare', '1', '223', null);
INSERT INTO "public"."palabras" VALUES ('story', 'historia', 'história', '1', '224', null);
INSERT INTO "public"."palabras" VALUES ('system', 'sistema', 'sistema', '1', '225', null);
INSERT INTO "public"."palabras" VALUES ('train', 'tren', 'trem', '1', '226', null);
INSERT INTO "public"."palabras" VALUES ('use', 'uso', 'usar', '1', '227', null);
INSERT INTO "public"."palabras" VALUES ('visit', 'visita', 'visita', '1', '228', null);
INSERT INTO "public"."palabras" VALUES ('voice', 'voz', 'voz', '1', '229', null);
INSERT INTO "public"."palabras" VALUES ('war', 'guerra', 'guerra', '1', '230', 'http://i.giphy.com/xcRw92jJZ0NCo.gif');
INSERT INTO "public"."palabras" VALUES ('water', 'agua', 'água', '1', '231', null);
INSERT INTO "public"."palabras" VALUES ('way', 'camino', 'caminho', '1', '232', null);
INSERT INTO "public"."palabras" VALUES ('week', 'semana', 'semana', '1', '233', null);
INSERT INTO "public"."palabras" VALUES ('wife', 'esposa', 'esposa', '1', '234', null);
INSERT INTO "public"."palabras" VALUES ('woman', 'mujer', 'mulheres', '1', '235', null);
INSERT INTO "public"."palabras" VALUES ('work', 'trabajo', 'trabalho', '1', '236', null);
INSERT INTO "public"."palabras" VALUES ('year', 'año', 'ano', '1', '237', null);
INSERT INTO "public"."palabras" VALUES ('yes', 'si', 'sim', '1', '238', null);
INSERT INTO "public"."palabras" VALUES ('you', 'usted', 'você', '1', '239', null);
INSERT INTO "public"."palabras" VALUES ('young', 'joven', 'jovem', '1', '240', 'http://i.giphy.com/h01OpEeFWverS.gif');
INSERT INTO "public"."palabras" VALUES ('your', 'tu', 'seu', '1', '241', null);
INSERT INTO "public"."palabras" VALUES ('a', 'un, una', 'uma', '2', '242', null);
INSERT INTO "public"."palabras" VALUES ('about', 'acerca de', 'sobre', '2', '243', null);
INSERT INTO "public"."palabras" VALUES ('accept', 'aceptar', 'aceitar', '2', '244', null);
INSERT INTO "public"."palabras" VALUES ('according', 'de acuerdo', 'segundo', '2', '245', null);
INSERT INTO "public"."palabras" VALUES ('account', 'cuenta', 'conta', '2', '246', null);
INSERT INTO "public"."palabras" VALUES ('add', 'aumentar', 'adicionar', '2', '247', null);
INSERT INTO "public"."palabras" VALUES ('advance', 'avanzar', 'avançar', '2', '248', null);
INSERT INTO "public"."palabras" VALUES ('after', 'después', 'depois de', '2', '249', null);
INSERT INTO "public"."palabras" VALUES ('again', 'de nuevo', 'mais uma vez', '2', '250', 'http://i.giphy.com/13MCWeJPQtkdVe.gif');
INSERT INTO "public"."palabras" VALUES ('age', 'edad', 'idade', '2', '251', null);
INSERT INTO "public"."palabras" VALUES ('agree', 'de acuerdo', 'concordar', '2', '252', null);
INSERT INTO "public"."palabras" VALUES ('almost', 'casi', 'quase', '2', '253', null);
INSERT INTO "public"."palabras" VALUES ('alone', 'solo', 'sozinho', '2', '254', null);
INSERT INTO "public"."palabras" VALUES ('also', 'también', 'também', '2', '255', null);
INSERT INTO "public"."palabras" VALUES ('am', 'soy, estoy', 'sou', '2', '256', null);
INSERT INTO "public"."palabras" VALUES ('amount', 'cantidad', 'quantidade', '2', '257', null);
INSERT INTO "public"."palabras" VALUES ('an', 'un, una', 'a', '2', '258', null);
INSERT INTO "public"."palabras" VALUES ('another', 'otro', 'outro', '2', '259', null);
INSERT INTO "public"."palabras" VALUES ('answer', 'respuesta', 'responda', '2', '260', 'http://i.giphy.com/ngyRZcPbJim4g.gif');
INSERT INTO "public"."palabras" VALUES ('around', 'alrededor', 'por aí', '2', '261', null);
INSERT INTO "public"."palabras" VALUES ('ask', 'preguntar', 'perguntar', '2', '262', null);
INSERT INTO "public"."palabras" VALUES ('attempt', 'intento', 'tentativa', '2', '263', null);
INSERT INTO "public"."palabras" VALUES ('back', 'espalda, atrás', 'costas', '2', '264', null);
INSERT INTO "public"."palabras" VALUES ('bank', 'banco', 'banco', '2', '265', null);
INSERT INTO "public"."palabras" VALUES ('bean', 'frijol', 'feijão', '2', '266', null);
INSERT INTO "public"."palabras" VALUES ('because', 'porque', 'porque', '2', '267', null);
INSERT INTO "public"."palabras" VALUES ('before', 'antes', 'antes', '2', '268', null);
INSERT INTO "public"."palabras" VALUES ('believe', 'creer', 'acreditar', '2', '269', null);
INSERT INTO "public"."palabras" VALUES ('below', 'debajo', 'abaixo', '2', '270', 'http://i.giphy.com/rypyVNU547qrC.gif');
INSERT INTO "public"."palabras" VALUES ('bill', 'cuenta', 'conta', '2', '271', null);
INSERT INTO "public"."palabras" VALUES ('blood', 'sangre', 'sangue', '2', '272', null);
INSERT INTO "public"."palabras" VALUES ('bridge', 'puente', 'ponte', '2', '273', null);
INSERT INTO "public"."palabras" VALUES ('broken', 'roto', 'partido', '2', '274', null);
INSERT INTO "public"."palabras" VALUES ('build', 'construir', 'construir', '2', '275', null);
INSERT INTO "public"."palabras" VALUES ('burn', 'quemar', 'queimar', '2', '276', null);
INSERT INTO "public"."palabras" VALUES ('busy', 'ocupado', 'ocupado', '2', '277', null);
INSERT INTO "public"."palabras" VALUES ('but', 'pero', 'mas', '2', '278', null);
INSERT INTO "public"."palabras" VALUES ('call', 'llamar', 'ligar', '2', '279', null);
INSERT INTO "public"."palabras" VALUES ('came', 'vino', 'veio', '2', '280', 'http://i.giphy.com/12m6YBQBVVPMK4.gif');
INSERT INTO "public"."palabras" VALUES ('can''t', 'no poder', 'não pode', '2', '281', null);
INSERT INTO "public"."palabras" VALUES ('care', 'cuidado', 'cuidado', '2', '282', null);
INSERT INTO "public"."palabras" VALUES ('case', 'caso', 'caso', '2', '283', null);
INSERT INTO "public"."palabras" VALUES ('cause', 'causa', 'causa', '2', '284', null);
INSERT INTO "public"."palabras" VALUES ('century', 'siglo', 'século', '2', '285', null);
INSERT INTO "public"."palabras" VALUES ('chain', 'cadena', 'corrente', '2', '286', null);
INSERT INTO "public"."palabras" VALUES ('chair', 'silla', 'cadeira', '2', '287', null);
INSERT INTO "public"."palabras" VALUES ('child', 'niño', 'criança', '2', '288', null);
INSERT INTO "public"."palabras" VALUES ('choose', 'escoger', 'escolher', '2', '289', null);
INSERT INTO "public"."palabras" VALUES ('clean', 'limpiar', 'limpar', '2', '290', 'http://i.giphy.com/3o6Ztc0dkvdss8lA2s.gif');
INSERT INTO "public"."palabras" VALUES ('clear', 'claro', 'claro', '2', '291', null);
INSERT INTO "public"."palabras" VALUES ('close', 'cerrar', 'fechar', '2', '292', null);
INSERT INTO "public"."palabras" VALUES ('club', 'club', 'clube', '2', '293', null);
INSERT INTO "public"."palabras" VALUES ('coat', 'saco', 'casaco', '2', '294', null);
INSERT INTO "public"."palabras" VALUES ('cook', 'cocinar', 'cozinhar', '2', '295', null);
INSERT INTO "public"."palabras" VALUES ('corner', 'esquina', 'canto', '2', '296', null);
INSERT INTO "public"."palabras" VALUES ('country', 'país', 'país', '2', '297', null);
INSERT INTO "public"."palabras" VALUES ('cut', 'cortar', 'cortar', '2', '298', null);
INSERT INTO "public"."palabras" VALUES ('dark', 'obscuro', 'escuro', '2', '299', null);
INSERT INTO "public"."palabras" VALUES ('dead', 'muerto', 'morto', '2', '300', 'http://i.giphy.com/8AQR3cbrA5i9i.gif');
INSERT INTO "public"."palabras" VALUES ('degree', 'grado', 'grau', '2', '301', null);
INSERT INTO "public"."palabras" VALUES ('device', 'dispositivo', 'dispositivo', '2', '302', null);
INSERT INTO "public"."palabras" VALUES ('dinner', 'cena', 'jantar', '2', '303', null);
INSERT INTO "public"."palabras" VALUES ('done', 'hecho', 'feito', '2', '304', null);
INSERT INTO "public"."palabras" VALUES ('dream', 'sueño', 'sonho', '2', '305', null);
INSERT INTO "public"."palabras" VALUES ('drive', 'manejar', 'dirigir', '2', '306', null);
INSERT INTO "public"."palabras" VALUES ('due', 'deber dinero', 'devido', '2', '307', null);
INSERT INTO "public"."palabras" VALUES ('duty', 'deber moral', 'dever moral', '2', '308', null);
INSERT INTO "public"."palabras" VALUES ('early', 'temprano', 'cedo', '2', '309', null);
INSERT INTO "public"."palabras" VALUES ('eat', 'comer', 'comer', '2', '310', 'http://i.giphy.com/MMQrQQ87G2MmY.gif');
INSERT INTO "public"."palabras" VALUES ('eight', 'ocho', 'oito', '2', '311', null);
INSERT INTO "public"."palabras" VALUES ('else', 'también', 'outro', '2', '312', null);
INSERT INTO "public"."palabras" VALUES ('enjoy', 'gozar', 'apreciar', '2', '313', null);
INSERT INTO "public"."palabras" VALUES ('even', 'igual', 'até', '2', '314', null);
INSERT INTO "public"."palabras" VALUES ('except', 'excepto', 'exceto', '2', '315', null);
INSERT INTO "public"."palabras" VALUES ('explain', 'explicar', 'explicar', '2', '316', null);
INSERT INTO "public"."palabras" VALUES ('fact', 'hecho', 'fato', '2', '317', null);
INSERT INTO "public"."palabras" VALUES ('fall', 'caer', 'cair', '2', '318', null);
INSERT INTO "public"."palabras" VALUES ('fancy', 'lindo', 'chique', '2', '319', null);
INSERT INTO "public"."palabras" VALUES ('fat', 'gordo', 'gordo', '2', '320', 'http://i.giphy.com/Gsynyb0RFF9zW.gif');
INSERT INTO "public"."palabras" VALUES ('feel', 'sentir', 'sentir', '2', '321', null);
INSERT INTO "public"."palabras" VALUES ('fellow', 'individuo', 'companheiro', '2', '322', null);
INSERT INTO "public"."palabras" VALUES ('field', 'campo', 'campo', '2', '323', null);
INSERT INTO "public"."palabras" VALUES ('figure', 'figura', 'figura', '2', '324', null);
INSERT INTO "public"."palabras" VALUES ('fine', 'perfecto', 'bem', '2', '325', null);
INSERT INTO "public"."palabras" VALUES ('finger', 'dedo', 'dedo', '2', '326', null);
INSERT INTO "public"."palabras" VALUES ('fire', 'fuego', 'fogo', '2', '327', null);
INSERT INTO "public"."palabras" VALUES ('fish', 'pescado', 'peixe', '2', '328', null);
INSERT INTO "public"."palabras" VALUES ('delight', 'deleite', 'prazer', '2', '329', null);
INSERT INTO "public"."palabras" VALUES ('desire', 'deseo', 'desejo', '2', '330', 'http://i.giphy.com/DYH297XiCS2Ck.gif');
INSERT INTO "public"."palabras" VALUES ('destroy', 'destruir', 'destruir', '2', '331', null);
INSERT INTO "public"."palabras" VALUES ('did', 'hizo', 'fez', '2', '332', null);
INSERT INTO "public"."palabras" VALUES ('die', 'morir', 'morrer', '2', '333', null);
INSERT INTO "public"."palabras" VALUES ('discover', 'descubrir', 'descobrir', '2', '334', null);
INSERT INTO "public"."palabras" VALUES ('does', 'hace', 'faz', '2', '335', null);
INSERT INTO "public"."palabras" VALUES ('doubt', 'duda', 'dúvida', '2', '336', null);
INSERT INTO "public"."palabras" VALUES ('down', 'abajo', 'baixa', '2', '337', null);
INSERT INTO "public"."palabras" VALUES ('dream', 'sueño', 'sonho', '2', '338', null);
INSERT INTO "public"."palabras" VALUES ('dress', 'vestido', 'vestir', '2', '339', null);
INSERT INTO "public"."palabras" VALUES ('drop', 'gota', 'solta', '2', '340', 'http://i.giphy.com/kezzYE1KpyYxi.gif');
INSERT INTO "public"."palabras" VALUES ('dry', 'secar', 'seco', '2', '341', null);
INSERT INTO "public"."palabras" VALUES ('during', 'durante', 'durante', '2', '342', null);
INSERT INTO "public"."palabras" VALUES ('dust', 'polvo', 'poeira', '2', '343', null);
INSERT INTO "public"."palabras" VALUES ('each', 'cada', 'cada', '2', '344', null);
INSERT INTO "public"."palabras" VALUES ('ear', 'oreja', 'orelha', '2', '345', null);
INSERT INTO "public"."palabras" VALUES ('earth', 'tierra', 'terra', '2', '346', null);
INSERT INTO "public"."palabras" VALUES ('east', 'este', 'leste', '2', '347', null);
INSERT INTO "public"."palabras" VALUES ('easy', 'fácil', 'fácil', '2', '348', null);
INSERT INTO "public"."palabras" VALUES ('edge', 'filo', 'Beira', '2', '349', null);
INSERT INTO "public"."palabras" VALUES ('effort', 'esfuerzo', 'esforço', '2', '350', 'http://i.giphy.com/xTiTnz33weTH3K8Uvu.gif');
INSERT INTO "public"."palabras" VALUES ('egg', 'huevo', 'ovo', '2', '351', null);
INSERT INTO "public"."palabras" VALUES ('either', 'tampoco', 'ou', '2', '352', null);
INSERT INTO "public"."palabras" VALUES ('end', 'fin', 'fim', '2', '353', null);
INSERT INTO "public"."palabras" VALUES ('enough', 'suficiente', 'o suficiente', '2', '354', null);
INSERT INTO "public"."palabras" VALUES ('enter', 'entrar', 'entrar', '2', '355', null);
INSERT INTO "public"."palabras" VALUES ('equal', 'igual', 'igual', '2', '356', null);
INSERT INTO "public"."palabras" VALUES ('evening', 'tarde', 'tarde', '2', '357', null);
INSERT INTO "public"."palabras" VALUES ('ever', 'siempre', 'sempre', '2', '358', null);
INSERT INTO "public"."palabras" VALUES ('every', 'todos', 'cada', '2', '359', null);
INSERT INTO "public"."palabras" VALUES ('expect', 'esperar', 'Espero', '2', '360', 'http://i.giphy.com/10cqKjOR7piLAI.gif');
INSERT INTO "public"."palabras" VALUES ('eye', 'ojo', 'olho', '2', '361', null);
INSERT INTO "public"."palabras" VALUES ('face', 'cara', 'cara', '2', '362', null);
INSERT INTO "public"."palabras" VALUES ('fail', 'fallar', 'falhou', '2', '363', null);
INSERT INTO "public"."palabras" VALUES ('fair', 'justa', 'justo', '2', '364', null);
INSERT INTO "public"."palabras" VALUES ('famous', 'famoso', 'famoso', '2', '365', null);
INSERT INTO "public"."palabras" VALUES ('far', 'lejos', 'longe', '2', '366', null);
INSERT INTO "public"."palabras" VALUES ('farm', 'granja', 'fazenda', '2', '367', null);
INSERT INTO "public"."palabras" VALUES ('fast', 'rápido', 'velozes', '2', '368', null);
INSERT INTO "public"."palabras" VALUES ('fear', 'temor', 'medo', '2', '369', null);
INSERT INTO "public"."palabras" VALUES ('feed', 'alimentar', 'alimentação', '2', '370', 'http://i.giphy.com/2xgzOPvrWW7hm.gif');
INSERT INTO "public"."palabras" VALUES ('fellow', 'compañero', 'companheiro', '2', '371', null);
INSERT INTO "public"."palabras" VALUES ('felt', 'sintió', 'sentiu', '2', '372', null);
INSERT INTO "public"."palabras" VALUES ('fence', 'cerca', 'cerca', '2', '373', null);
INSERT INTO "public"."palabras" VALUES ('few', 'pocos', 'poucos', '2', '374', null);
INSERT INTO "public"."palabras" VALUES ('fight', 'pelear', 'luta', '2', '375', null);
INSERT INTO "public"."palabras" VALUES ('fill', 'llenar', 'preencher', '2', '376', null);
INSERT INTO "public"."palabras" VALUES ('find', 'encontrar', 'encontrar', '2', '377', null);
INSERT INTO "public"."palabras" VALUES ('fine', 'fino', 'fino', '2', '378', null);
INSERT INTO "public"."palabras" VALUES ('firm', 'firme', 'empresa', '2', '379', null);
INSERT INTO "public"."palabras" VALUES ('fit', 'ajustar', 'caber', '2', '380', 'http://i.giphy.com/3o6Zt8MgUuvSbkZYWc.gif');
INSERT INTO "public"."palabras" VALUES ('fix', 'arreglar', 'consertar', '2', '381', null);
INSERT INTO "public"."palabras" VALUES ('flower', 'flor', 'flor', '2', '382', null);
INSERT INTO "public"."palabras" VALUES ('fly', 'volar', 'voar', '2', '383', null);
INSERT INTO "public"."palabras" VALUES ('follow', 'seguir', 'segue', '2', '384', null);
INSERT INTO "public"."palabras" VALUES ('forget', 'olvidar', 'esquecer', '2', '385', null);
INSERT INTO "public"."palabras" VALUES ('four', 'cuatro', 'quatro', '2', '386', null);
INSERT INTO "public"."palabras" VALUES ('from', 'desde', 'a partir de', '2', '387', null);
INSERT INTO "public"."palabras" VALUES ('further', 'distante', 'distante', '2', '388', null);
INSERT INTO "public"."palabras" VALUES ('gain', 'ganancia', 'ganho', '2', '389', null);
INSERT INTO "public"."palabras" VALUES ('gate', 'puerta', 'portão', '2', '390', 'http://i.giphy.com/TdfyKrN7HGTIY.gif');
INSERT INTO "public"."palabras" VALUES ('gather', 'reunir', 'reunir', '2', '391', null);
INSERT INTO "public"."palabras" VALUES ('give', 'dar', 'dar', '2', '392', null);
INSERT INTO "public"."palabras" VALUES ('given', 'dado, participio pasado', 'dado, particípio passado', '2', '393', null);
INSERT INTO "public"."palabras" VALUES ('glad', 'contento', 'contente', '2', '394', null);
INSERT INTO "public"."palabras" VALUES ('go', 'ir', 'ir', '2', '395', null);
INSERT INTO "public"."palabras" VALUES ('gold', 'oro', 'ouro', '2', '396', null);
INSERT INTO "public"."palabras" VALUES ('good', 'bueno', 'bom', '2', '397', null);
INSERT INTO "public"."palabras" VALUES ('grain', 'grano, semilla', 'grão', '2', '398', null);
INSERT INTO "public"."palabras" VALUES ('grave', 'sepultura', 'grave', '2', '399', null);
INSERT INTO "public"."palabras" VALUES ('ground', 'tierra, suelo', 'chão', '2', '400', 'http://i.giphy.com/3oEduVObV0nnnTSDCg.gif');
INSERT INTO "public"."palabras" VALUES ('guess', 'adivinar', 'adivinhar', '2', '401', null);
INSERT INTO "public"."palabras" VALUES ('guide', 'guía', 'guia', '2', '402', null);
INSERT INTO "public"."palabras" VALUES ('had', 'tenido', 'teve', '2', '403', null);
INSERT INTO "public"."palabras" VALUES ('hair', 'pelo', 'cabelo', '2', '404', null);
INSERT INTO "public"."palabras" VALUES ('hang', 'colgar', 'aguentar', '2', '405', null);
INSERT INTO "public"."palabras" VALUES ('has', 'tiene', 'tem', '2', '406', null);
INSERT INTO "public"."palabras" VALUES ('have', 'tener', 'ter', '2', '407', null);
INSERT INTO "public"."palabras" VALUES ('he', 'el', 'ele', '2', '408', null);
INSERT INTO "public"."palabras" VALUES ('health', 'salud', 'saúde', '2', '409', null);
INSERT INTO "public"."palabras" VALUES ('hear', 'oír', 'ouvir', '2', '410', 'http://i.giphy.com/peMsofRVIS4WQ.gif');
INSERT INTO "public"."palabras" VALUES ('heard', 'oído', 'ouviu', '2', '411', null);
INSERT INTO "public"."palabras" VALUES ('heat', 'calor', 'calor', '2', '412', null);
INSERT INTO "public"."palabras" VALUES ('heavy', 'pesado', 'pesado', '2', '413', null);
INSERT INTO "public"."palabras" VALUES ('held', 'sostener', 'mantido', '2', '414', null);
INSERT INTO "public"."palabras" VALUES ('hill', 'colina', 'monte', '2', '415', null);
INSERT INTO "public"."palabras" VALUES ('hit', 'golpear', 'acertar', '2', '416', null);
INSERT INTO "public"."palabras" VALUES ('hold', 'sujetar', 'segurar', '2', '417', null);
INSERT INTO "public"."palabras" VALUES ('hot', 'caliente', 'quente', '2', '418', null);
INSERT INTO "public"."palabras" VALUES ('however', 'aunque, como siempre', 'porém', '2', '419', null);
INSERT INTO "public"."palabras" VALUES ('hungry', 'hambre', 'fome', '2', '420', 'http://i.giphy.com/tGokBeqpHuSgE.gif');
INSERT INTO "public"."palabras" VALUES ('hunt', 'cazar', 'caçar', '2', '421', null);
INSERT INTO "public"."palabras" VALUES ('hurt', 'lastimar', 'ferir', '2', '422', null);
INSERT INTO "public"."palabras" VALUES ('ill', 'enfermo', 'doente', '2', '423', null);
INSERT INTO "public"."palabras" VALUES ('in', 'dentro', 'dentro', '2', '424', null);
INSERT INTO "public"."palabras" VALUES ('inch', 'pulgada', 'polegada', '2', '425', null);
INSERT INTO "public"."palabras" VALUES ('indeed', 'realmente', 'de fato', '2', '426', null);
INSERT INTO "public"."palabras" VALUES ('instead', 'en cambio de', 'ao invés', '2', '427', null);
INSERT INTO "public"."palabras" VALUES ('it''s', 'posesivo de esto', 'Está', '2', '428', null);
INSERT INTO "public"."palabras" VALUES ('join', 'unirse', 'juntar', '2', '429', null);
INSERT INTO "public"."palabras" VALUES ('joy', 'alegría', 'alegria', '2', '430', 'http://i.giphy.com/vSG7wQ7sAuQ6I.gif');
INSERT INTO "public"."palabras" VALUES ('judge', 'juez', 'juiz', '2', '431', null);
INSERT INTO "public"."palabras" VALUES ('kept', 'guardar', 'guardado', '2', '432', null);
INSERT INTO "public"."palabras" VALUES ('kind', 'amable', 'amável', '2', '433', null);
INSERT INTO "public"."palabras" VALUES ('king', 'rey', 'rei', '2', '434', null);
INSERT INTO "public"."palabras" VALUES ('knee', 'rodilla', 'joelho', '2', '435', null);
INSERT INTO "public"."palabras" VALUES ('know', 'saber', 'conhecer', '2', '436', null);
INSERT INTO "public"."palabras" VALUES ('known', 'sabido', 'conhecido', '2', '437', null);
INSERT INTO "public"."palabras" VALUES ('late', 'tarde', 'atrasado', '2', '438', null);
INSERT INTO "public"."palabras" VALUES ('lay', 'poner', 'pôr', '2', '439', null);
INSERT INTO "public"."palabras" VALUES ('lead', 'dirigir', 'conduzir', '2', '440', 'http://i.giphy.com/13wAmg8pGU2olq.gif');
INSERT INTO "public"."palabras" VALUES ('led', 'conducir', 'conduzir', '2', '441', null);
INSERT INTO "public"."palabras" VALUES ('leg', 'pierna', 'perna', '2', '442', null);
INSERT INTO "public"."palabras" VALUES ('let', 'dejar', 'deixar', '2', '443', null);
INSERT INTO "public"."palabras" VALUES ('life', 'vida', 'vida', '2', '444', null);
INSERT INTO "public"."palabras" VALUES ('lift', 'levantar', 'levantar', '2', '445', null);
INSERT INTO "public"."palabras" VALUES ('line', 'línea', 'linha', '2', '446', null);
INSERT INTO "public"."palabras" VALUES ('lip', 'labio', 'lábio', '2', '447', null);
INSERT INTO "public"."palabras" VALUES ('list', 'lista', 'lista', '2', '448', null);
INSERT INTO "public"."palabras" VALUES ('live', 'vivir', 'viver', '2', '449', null);
INSERT INTO "public"."palabras" VALUES ('lonely', 'solitario', 'solitário', '2', '450', 'http://i.giphy.com/b09xElu8in7Lq.gif');
INSERT INTO "public"."palabras" VALUES ('loss', 'perdida', 'perda', '2', '451', null);
INSERT INTO "public"."palabras" VALUES ('lost', 'perdido', 'perdido', '2', '452', null);
INSERT INTO "public"."palabras" VALUES ('mad', 'loco', 'louco', '2', '453', null);
INSERT INTO "public"."palabras" VALUES ('make', 'hacer', 'fazer', '2', '454', null);
INSERT INTO "public"."palabras" VALUES ('mark', 'marcar', 'marca', '2', '455', null);
INSERT INTO "public"."palabras" VALUES ('may', 'mayo o poder', 'Maio, pode', '2', '456', null);
INSERT INTO "public"."palabras" VALUES ('measure', 'medida', 'medida', '2', '457', null);
INSERT INTO "public"."palabras" VALUES ('met', 'conocerse, encontrar', 'conheceu', '2', '458', null);
INSERT INTO "public"."palabras" VALUES ('middle', 'medio', 'meio', '2', '459', null);
INSERT INTO "public"."palabras" VALUES ('might', 'poder de voluntad', 'poderia', '2', '460', 'http://i.giphy.com/XQ1FwjRKun4nS.gif');
INSERT INTO "public"."palabras" VALUES ('mile', 'milla', 'milha', '2', '461', null);
INSERT INTO "public"."palabras" VALUES ('mill', 'molino', 'moinho', '2', '462', null);
INSERT INTO "public"."palabras" VALUES ('mine', 'mío, mía', 'meu', '2', '463', null);
INSERT INTO "public"."palabras" VALUES ('moon', 'luna', 'lua', '2', '464', null);
INSERT INTO "public"."palabras" VALUES ('most', 'más', 'a maioria', '2', '465', null);
INSERT INTO "public"."palabras" VALUES ('move', 'mover', 'mover', '2', '466', null);
INSERT INTO "public"."palabras" VALUES ('need', 'necesidad', 'necessidade', '2', '467', null);
INSERT INTO "public"."palabras" VALUES ('neither', 'ninguno', 'nem', '2', '468', null);
INSERT INTO "public"."palabras" VALUES ('news', 'noticia', 'notícia', '2', '469', null);
INSERT INTO "public"."palabras" VALUES ('nice', 'simpático, bonito', 'bom', '2', '470', 'http://i.giphy.com/l4hLHJCwpscYLkArm.gif');
INSERT INTO "public"."palabras" VALUES ('nine', 'nueve', 'nove', '2', '471', null);
INSERT INTO "public"."palabras" VALUES ('none', 'nadie, nada', 'nenhum', '2', '472', null);
INSERT INTO "public"."palabras" VALUES ('noon', 'medio día', 'meio-dia', '2', '473', null);
INSERT INTO "public"."palabras" VALUES ('nor', 'ni', 'nem', '2', '474', null);
INSERT INTO "public"."palabras" VALUES ('nose', 'nariz', 'nariz', '2', '475', null);
INSERT INTO "public"."palabras" VALUES ('note', 'nota', 'Nota', '2', '476', null);
INSERT INTO "public"."palabras" VALUES ('now', 'ahora', 'agora', '2', '477', null);
INSERT INTO "public"."palabras" VALUES ('often', 'frecuente', 'frequentemente', '2', '478', null);
INSERT INTO "public"."palabras" VALUES ('once', 'una vez', 'uma vez', '2', '479', null);
INSERT INTO "public"."palabras" VALUES ('on', 'en', 'em', '2', '480', 'http://i.giphy.com/P4JxHWpuueBag.gif');
INSERT INTO "public"."palabras" VALUES ('other', 'otro', 'de outros', '2', '481', null);
INSERT INTO "public"."palabras" VALUES ('ought', 'deber', 'dever', '2', '482', null);
INSERT INTO "public"."palabras" VALUES ('outside', 'afuera', 'fora', '2', '483', null);
INSERT INTO "public"."palabras" VALUES ('over', 'sobre', 'sobre', '2', '484', null);
INSERT INTO "public"."palabras" VALUES ('pain', 'dolor', 'dor', '2', '485', null);
INSERT INTO "public"."palabras" VALUES ('part', 'parte', 'parte', '2', '486', null);
INSERT INTO "public"."palabras" VALUES ('party', 'fiesta', 'festa', '2', '487', null);
INSERT INTO "public"."palabras" VALUES ('pass', 'pasar', 'passar', '2', '488', null);
INSERT INTO "public"."palabras" VALUES ('past', 'pasado', 'passado', '2', '489', null);
INSERT INTO "public"."palabras" VALUES ('perhaps', 'quizás', 'possivelmente', '2', '490', 'http://i.giphy.com/NrtbALXtMRLyg.gif');
INSERT INTO "public"."palabras" VALUES ('pick', 'recoger', 'escolher', '2', '491', null);
INSERT INTO "public"."palabras" VALUES ('piece', 'pedazo', 'peça', '2', '492', null);
INSERT INTO "public"."palabras" VALUES ('plain', 'plano', 'plano', '2', '493', null);
INSERT INTO "public"."palabras" VALUES ('play', 'jugar', 'jogar', '2', '494', null);
INSERT INTO "public"."palabras" VALUES ('pleasant', 'placentero', 'agradável', '2', '495', null);
INSERT INTO "public"."palabras" VALUES ('pleasure', 'placer', 'prazer', '2', '496', null);
INSERT INTO "public"."palabras" VALUES ('poor', 'pobre', 'pobre', '2', '497', null);
INSERT INTO "public"."palabras" VALUES ('post', 'enviar', 'postar', '2', '498', null);
INSERT INTO "public"."palabras" VALUES ('power', 'poder', 'poder', '2', '499', null);
INSERT INTO "public"."palabras" VALUES ('pray', 'orar', 'orar', '2', '500', 'https://media.giphy.com/media/ldcfCMdHGDJNC/giphy.gif');
INSERT INTO "public"."palabras" VALUES ('pretty', 'lindo', 'lindo', '2', '501', null);
INSERT INTO "public"."palabras" VALUES ('price', 'precio', 'preço', '2', '502', null);
INSERT INTO "public"."palabras" VALUES ('proud', 'orgulloso', 'orgulhoso', '2', '503', null);
INSERT INTO "public"."palabras" VALUES ('pull', 'empujar', 'puxar', '2', '504', null);
INSERT INTO "public"."palabras" VALUES ('put', 'poner', 'colocar', '2', '505', null);
INSERT INTO "public"."palabras" VALUES ('queen', 'reina', 'rainha', '2', '506', null);
INSERT INTO "public"."palabras" VALUES ('quick', 'rápido', 'rápido', '2', '507', null);
INSERT INTO "public"."palabras" VALUES ('quiet', 'tranquilo', 'quieto', '2', '508', null);
INSERT INTO "public"."palabras" VALUES ('quite', 'bastante', 'bastante', '2', '509', null);
INSERT INTO "public"."palabras" VALUES ('rain', 'lluvia', 'chuva', '2', '510', 'http://i.giphy.com/1hVi7JFFzplHW.gif');
INSERT INTO "public"."palabras" VALUES ('raise', 'levantar', 'levantar', '2', '511', null);
INSERT INTO "public"."palabras" VALUES ('ran', 'corrió', 'correu', '2', '512', null);
INSERT INTO "public"."palabras" VALUES ('rather', 'más bien', 'em vez', '2', '513', null);
INSERT INTO "public"."palabras" VALUES ('uncle', 'tío', 'tio', '2', '514', null);
INSERT INTO "public"."palabras" VALUES ('five', 'cinco', 'cinco', '2', '515', null);
INSERT INTO "public"."palabras" VALUES ('floor', 'piso', 'chão', '2', '516', null);
INSERT INTO "public"."palabras" VALUES ('fool', 'tonto', 'idiota', '2', '517', null);
INSERT INTO "public"."palabras" VALUES ('foreign', 'extranjero', 'estrangeiro', '2', '518', null);
INSERT INTO "public"."palabras" VALUES ('forest', 'bosque', 'floresta', '2', '519', null);
INSERT INTO "public"."palabras" VALUES ('forward', 'adelante', 'adiante', '2', '520', 'http://i.giphy.com/3oEdv73lmCG5GGiWxa.gif');
INSERT INTO "public"."palabras" VALUES ('found', 'encontró', 'encontrado', '2', '521', null);
INSERT INTO "public"."palabras" VALUES ('fresh', 'fresco', 'fresco', '2', '522', null);
INSERT INTO "public"."palabras" VALUES ('full', 'lleno', 'cheio', '2', '523', null);
INSERT INTO "public"."palabras" VALUES ('gave', 'dio', 'deu', '2', '524', null);
INSERT INTO "public"."palabras" VALUES ('gentle', 'gentil', 'suave', '2', '525', null);
INSERT INTO "public"."palabras" VALUES ('get', 'conseguir', 'obter', '2', '526', null);
INSERT INTO "public"."palabras" VALUES ('gift', 'regalo', 'presente', '2', '527', null);
INSERT INTO "public"."palabras" VALUES ('god', 'dios', 'deus', '2', '528', null);
INSERT INTO "public"."palabras" VALUES ('gone', 'ido', 'foi', '2', '529', null);
INSERT INTO "public"."palabras" VALUES ('got', 'alcanzado', 'obteve', '2', '530', 'http://i.giphy.com/1S6xghiGMc6Hu.gif');
INSERT INTO "public"."palabras" VALUES ('gray', 'gris', 'cinza', '2', '531', null);
INSERT INTO "public"."palabras" VALUES ('grew', 'creció', 'cresceu', '2', '532', null);
INSERT INTO "public"."palabras" VALUES ('grow', 'crecer', 'crescer', '2', '533', null);
INSERT INTO "public"."palabras" VALUES ('gun', 'arma de fuego', 'pistola', '2', '534', null);
INSERT INTO "public"."palabras" VALUES ('happen', 'suceder, pasar', 'acontecer', '2', '535', null);
INSERT INTO "public"."palabras" VALUES ('hard', 'difícil', 'difícil', '2', '536', null);
INSERT INTO "public"."palabras" VALUES ('hat', 'sombrero', 'sombreiro', '2', '537', null);
INSERT INTO "public"."palabras" VALUES ('he', 'él', 'ele', '2', '538', null);
INSERT INTO "public"."palabras" VALUES ('head', 'cabeza', 'cabeça', '2', '539', null);
INSERT INTO "public"."palabras" VALUES ('heart', 'corazón', 'coração', '2', '540', 'http://i.giphy.com/6pSJGZW0ZmbUA.gif');
INSERT INTO "public"."palabras" VALUES ('heaven', 'cielo', 'céu', '2', '541', null);
INSERT INTO "public"."palabras" VALUES ('height', 'altura', 'altura', '2', '542', null);
INSERT INTO "public"."palabras" VALUES ('help', 'ayuda', 'ajuda', '2', '543', null);
INSERT INTO "public"."palabras" VALUES ('her', 'ella', 'dela', '2', '544', null);
INSERT INTO "public"."palabras" VALUES ('here', 'aquí', 'Aqui', '2', '545', null);
INSERT INTO "public"."palabras" VALUES ('high', 'altura', 'Alto', '2', '546', null);
INSERT INTO "public"."palabras" VALUES ('him', 'el', 'ele', '2', '547', null);
INSERT INTO "public"."palabras" VALUES ('his', 'de él', 'dele', '2', '548', null);
INSERT INTO "public"."palabras" VALUES ('hole', 'hueco', 'buraco', '2', '549', null);
INSERT INTO "public"."palabras" VALUES ('hope', 'esperanza', 'esperança', '2', '550', 'http://i.giphy.com/JKfAk6hieK4uY.gif');
INSERT INTO "public"."palabras" VALUES ('horse', 'caballo', 'cavalo', '2', '551', null);
INSERT INTO "public"."palabras" VALUES ('house', 'casa', 'casa', '2', '552', null);
INSERT INTO "public"."palabras" VALUES ('how', 'como?', 'como?', '2', '553', null);
INSERT INTO "public"."palabras" VALUES ('hundred', 'ciento', 'cem', '2', '554', null);
INSERT INTO "public"."palabras" VALUES ('hurry', 'prisa', 'pressa', '2', '555', null);
INSERT INTO "public"."palabras" VALUES ('husband', 'marido', 'marido', '2', '556', null);
INSERT INTO "public"."palabras" VALUES ('ice', 'hielo', 'gelo', '2', '557', null);
INSERT INTO "public"."palabras" VALUES ('if', 'sí, condicional', 'E se', '2', '558', null);
INSERT INTO "public"."palabras" VALUES ('increase', 'aumentar', 'aumentar', '2', '559', null);
INSERT INTO "public"."palabras" VALUES ('into', 'dentro', 'dentro', '2', '560', 'http://i.giphy.com/SQQ5VpVKhCM9O.gif');
INSERT INTO "public"."palabras" VALUES ('iron', 'hierro', 'ferro', '2', '561', null);
INSERT INTO "public"."palabras" VALUES ('job', 'empleo', 'emprego', '2', '562', null);
INSERT INTO "public"."palabras" VALUES ('journey', 'viaje', 'viagem', '2', '563', null);
INSERT INTO "public"."palabras" VALUES ('jump', 'saltar', 'pular', '2', '564', null);
INSERT INTO "public"."palabras" VALUES ('keep', 'mantener', 'guarda', '2', '565', null);
INSERT INTO "public"."palabras" VALUES ('kill', 'matar', 'matar', '2', '566', null);
INSERT INTO "public"."palabras" VALUES ('kitchen', 'cocina', 'cozinha', '2', '567', null);
INSERT INTO "public"."palabras" VALUES ('knew', 'supo', 'sabia', '2', '568', null);
INSERT INTO "public"."palabras" VALUES ('lake', 'lago', 'lago', '2', '569', null);
INSERT INTO "public"."palabras" VALUES ('land', 'tierra', 'terra', '2', '570', 'http://i.giphy.com/GHnc1Czk0Br20.gif');
INSERT INTO "public"."palabras" VALUES ('last', 'último', 'último', '2', '571', null);
INSERT INTO "public"."palabras" VALUES ('laugh', 'risa', 'rir', '2', '572', null);
INSERT INTO "public"."palabras" VALUES ('law', 'ley', 'lei', '2', '573', null);
INSERT INTO "public"."palabras" VALUES ('learn', 'aprender', 'aprender', '2', '574', null);
INSERT INTO "public"."palabras" VALUES ('leave', 'salir, dejar', 'sair', '2', '575', null);
INSERT INTO "public"."palabras" VALUES ('left', 'izquierda', 'esquerda', '2', '576', null);
INSERT INTO "public"."palabras" VALUES ('length', 'largo', 'comprimento', '2', '577', null);
INSERT INTO "public"."palabras" VALUES ('less', 'menor', 'menor', '2', '578', null);
INSERT INTO "public"."palabras" VALUES ('lie', 'mentira', 'mentira', '2', '579', null);
INSERT INTO "public"."palabras" VALUES ('like', 'gustar', 'gostar', '2', '580', 'http://i.giphy.com/9qMIBqOJrtvfW.gif');
INSERT INTO "public"."palabras" VALUES ('listen', 'escuchar', 'ouço', '2', '581', null);
INSERT INTO "public"."palabras" VALUES ('look', 'mirar', 'veja', '2', '582', null);
INSERT INTO "public"."palabras" VALUES ('lose', 'perder', 'perder', '2', '583', null);
INSERT INTO "public"."palabras" VALUES ('loud', 'sonido alto', 'alto', '2', '584', null);
INSERT INTO "public"."palabras" VALUES ('low', 'bajo', 'baixo', '2', '585', null);
INSERT INTO "public"."palabras" VALUES ('mail', 'correo', 'enviar', '2', '586', null);
INSERT INTO "public"."palabras" VALUES ('man', 'hombre', 'homem', '2', '587', null);
INSERT INTO "public"."palabras" VALUES ('many', 'muchos, muchas', 'muitos, muitas', '2', '588', null);
INSERT INTO "public"."palabras" VALUES ('march', 'marzo', 'março', '2', '589', null);
INSERT INTO "public"."palabras" VALUES ('marry', 'matrimonio', 'casar', '2', '590', 'http://i.giphy.com/dkGhBWE3SyzXW.gif');
INSERT INTO "public"."palabras" VALUES ('matter', 'asunto', 'assunto', '2', '591', null);
INSERT INTO "public"."palabras" VALUES ('mean', 'significado', 'significar', '2', '592', null);
INSERT INTO "public"."palabras" VALUES ('meet', 'encontrar', 'conheça', '2', '593', null);
INSERT INTO "public"."palabras" VALUES ('meeting', 'reunión', 'reunião', '2', '594', null);
INSERT INTO "public"."palabras" VALUES ('million', 'millón', 'milhão', '2', '595', null);
INSERT INTO "public"."palabras" VALUES ('mind', 'mente', 'mente', '2', '596', null);
INSERT INTO "public"."palabras" VALUES ('miss', 'señorita', 'senhorita', '2', '597', null);
INSERT INTO "public"."palabras" VALUES ('month', 'mes', 'mês', '2', '598', null);
INSERT INTO "public"."palabras" VALUES ('mouth', 'boca', 'boca', '2', '599', null);
INSERT INTO "public"."palabras" VALUES ('nature', 'naturaleza', 'natureza', '2', '600', 'http://i.giphy.com/WoYwgrfZP4yw8.gif');
INSERT INTO "public"."palabras" VALUES ('near', 'cercano', 'perto', '2', '601', null);
INSERT INTO "public"."palabras" VALUES ('neck', 'cuello', 'pescoço', '2', '602', null);
INSERT INTO "public"."palabras" VALUES ('able', 'hábil, capaz', 'capaz', '3', '603', null);
INSERT INTO "public"."palabras" VALUES ('above', 'encima', 'acima', '3', '604', null);
INSERT INTO "public"."palabras" VALUES ('across', 'a través de', 'através', '3', '605', null);
INSERT INTO "public"."palabras" VALUES ('afraid', 'asustado', 'receoso', '3', '606', null);
INSERT INTO "public"."palabras" VALUES ('against', 'contra', 'contra', '3', '607', null);
INSERT INTO "public"."palabras" VALUES ('ago', 'hace tiempo', 'atrás', '3', '608', null);
INSERT INTO "public"."palabras" VALUES ('all', 'todo', 'todos', '3', '609', null);
INSERT INTO "public"."palabras" VALUES ('allow', 'debajo', 'permitir', '3', '610', 'http://i.giphy.com/3oEduVObV0nnnTSDCg.gif');
INSERT INTO "public"."palabras" VALUES ('along', 'a lo largo', 'ao longo', '3', '611', null);
INSERT INTO "public"."palabras" VALUES ('although', 'aunque', 'Apesar', '3', '612', null);
INSERT INTO "public"."palabras" VALUES ('always', 'siempre', 'sempre', '3', '613', null);
INSERT INTO "public"."palabras" VALUES ('among', 'entre', 'entre', '3', '614', null);
INSERT INTO "public"."palabras" VALUES ('and', 'y', 'e', '3', '615', null);
INSERT INTO "public"."palabras" VALUES ('anger', 'cólera', 'raiva', '3', '616', null);
INSERT INTO "public"."palabras" VALUES ('any', 'cualquiera', 'qualquer', '3', '617', null);
INSERT INTO "public"."palabras" VALUES ('appear', 'aparecer', 'aparecer', '3', '618', null);
INSERT INTO "public"."palabras" VALUES ('are', 'son o estar', 'estamos', '3', '619', null);
INSERT INTO "public"."palabras" VALUES ('arm', 'brazo', 'braço', '3', '620', 'http://i.giphy.com/DpB9NBjny7jF1pd0yt2.gif');
INSERT INTO "public"."palabras" VALUES ('arrive', 'llegar', 'chegar', '3', '621', null);
INSERT INTO "public"."palabras" VALUES ('art', 'arte', 'arte', '3', '622', null);
INSERT INTO "public"."palabras" VALUES ('at', 'cerca de', 'em', '3', '623', null);
INSERT INTO "public"."palabras" VALUES ('away', 'lejos', 'longe', '3', '624', null);
INSERT INTO "public"."palabras" VALUES ('bag', 'bolsa', 'bolsa', '3', '625', null);
INSERT INTO "public"."palabras" VALUES ('bay', 'bahía', 'baía', '3', '626', null);
INSERT INTO "public"."palabras" VALUES ('beat', 'golpear', 'batida', '3', '627', null);
INSERT INTO "public"."palabras" VALUES ('became', 'convirtió', '"', null, '628', null);
INSERT INTO "public"."palabras" VALUES ('passou a ser"', '3', null, null, '629', null);
INSERT INTO "public"."palabras" VALUES ('become', 'volverse', 'tornar-se', '3', '630', 'http://i.giphy.com/c94M9O8hn6zdK.gif');
INSERT INTO "public"."palabras" VALUES ('began', 'empezó', 'começasse', '3', '631', null);
INSERT INTO "public"."palabras" VALUES ('behind', 'detrás', 'atrás', '3', '632', null);
INSERT INTO "public"."palabras" VALUES ('being', 'siendo', 'ser', '3', '633', null);
INSERT INTO "public"."palabras" VALUES ('belong', 'pertenecer', 'pertencer', '3', '634', null);
INSERT INTO "public"."palabras" VALUES ('beside', 'al lado', 'ao lado', '3', '635', null);
INSERT INTO "public"."palabras" VALUES ('between', 'entre', 'entre', '3', '636', null);
INSERT INTO "public"."palabras" VALUES ('beyond', 'más allá', 'além', '3', '637', null);
INSERT INTO "public"."palabras" VALUES ('big', 'grande', 'grande', '3', '638', null);
INSERT INTO "public"."palabras" VALUES ('bit', 'poco', 'pouco', '3', '639', null);
INSERT INTO "public"."palabras" VALUES ('black', 'negro', 'preto', '3', '640', 'http://i.giphy.com/12SXVd8bmXdSg0.gif');
INSERT INTO "public"."palabras" VALUES ('bless', 'bendecir', 'abençoar', '3', '641', null);
INSERT INTO "public"."palabras" VALUES ('blind', 'ciego', 'cego', '3', '642', null);
INSERT INTO "public"."palabras" VALUES ('blow', 'golpe, viento', 'golpe, soprar', '3', '643', null);
INSERT INTO "public"."palabras" VALUES ('board', 'tablero', 'borda', '3', '644', null);
INSERT INTO "public"."palabras" VALUES ('boat', 'bote', 'barco', '3', '645', null);
INSERT INTO "public"."palabras" VALUES ('bone', 'hueso', 'osso', '3', '646', null);
INSERT INTO "public"."palabras" VALUES ('born', 'nacer', 'nascermos', '3', '647', null);
INSERT INTO "public"."palabras" VALUES ('both', 'ambos', 'ambos', '3', '648', null);
INSERT INTO "public"."palabras" VALUES ('bottom', 'fondo', 'fundo', '3', '649', null);
INSERT INTO "public"."palabras" VALUES ('branch', 'ramificar', 'ramo', '3', '650', 'http://i.giphy.com/2Vp0UxNcA8TEQ.gif');
INSERT INTO "public"."palabras" VALUES ('bread', 'pan', 'pão', '3', '651', null);
INSERT INTO "public"."palabras" VALUES ('break', 'romper', 'pausa', '3', '652', null);
INSERT INTO "public"."palabras" VALUES ('breath', 'respirar', 'respiração', '3', '653', null);
INSERT INTO "public"."palabras" VALUES ('bright', 'brillar', 'brilhante', '3', '654', null);
INSERT INTO "public"."palabras" VALUES ('bring', 'traer', 'trazer', '3', '655', null);
INSERT INTO "public"."palabras" VALUES ('broad', 'ancho', 'amplo', '3', '656', null);
INSERT INTO "public"."palabras" VALUES ('brought', 'trajo', 'trouxe', '3', '657', null);
INSERT INTO "public"."palabras" VALUES ('brown', 'marrón', 'castanho', '3', '658', null);
INSERT INTO "public"."palabras" VALUES ('bug', 'error, bicho', 'erro, bicho', '3', '659', null);
INSERT INTO "public"."palabras" VALUES ('building', 'edificio', 'prédio', '3', '660', 'http://i.giphy.com/7eAvzJ0SBBzHy.gif');
INSERT INTO "public"."palabras" VALUES ('built', 'construido', 'construído', '3', '661', null);
INSERT INTO "public"."palabras" VALUES ('bus', 'bus', 'ônibus', '3', '662', null);
INSERT INTO "public"."palabras" VALUES ('butter', 'mantequilla', 'manteiga', '3', '663', null);
INSERT INTO "public"."palabras" VALUES ('buy', 'comprar', 'comprar', '3', '664', null);
INSERT INTO "public"."palabras" VALUES ('cake', 'pastel', 'bolo', '3', '665', null);
INSERT INTO "public"."palabras" VALUES ('carry', 'cargar, llevar', 'transportar', '3', '666', null);
INSERT INTO "public"."palabras" VALUES ('catch', 'coger', 'pegar', '3', '667', null);
INSERT INTO "public"."palabras" VALUES ('caught', 'atrapado', 'capturados', '3', '668', null);
INSERT INTO "public"."palabras" VALUES ('change', 'cambiar', 'alterar', '3', '669', null);
INSERT INTO "public"."palabras" VALUES ('charge', 'cargar', 'carregar', '3', '670', 'http://i.giphy.com/yb0wLO0hJcBWg.gif');
INSERT INTO "public"."palabras" VALUES ('chief', 'jefe', 'chefe', '3', '671', null);
INSERT INTO "public"."palabras" VALUES ('church', 'iglesia', 'Igreja', '3', '672', null);
INSERT INTO "public"."palabras" VALUES ('clothes', 'ropa', 'roupas', '3', '673', null);
INSERT INTO "public"."palabras" VALUES ('cloud', 'nube', 'nuvem', '3', '674', null);
INSERT INTO "public"."palabras" VALUES ('coal', 'carbón', 'carvão', '3', '675', null);
INSERT INTO "public"."palabras" VALUES ('cold', 'frio, resfrío', 'frio', '3', '676', null);
INSERT INTO "public"."palabras" VALUES ('come', 'ven', 'vir', '3', '677', null);
INSERT INTO "public"."palabras" VALUES ('contain', 'contener', 'conter', '3', '678', null);
INSERT INTO "public"."palabras" VALUES ('cool', 'fresco, atractivo', 'legal, frio', '3', '679', null);
INSERT INTO "public"."palabras" VALUES ('corn', 'maíz', 'milho', '3', '680', 'http://i.giphy.com/4nlBr430OSaru.gif');
INSERT INTO "public"."palabras" VALUES ('cost', 'costo', 'custo', '3', '681', null);
INSERT INTO "public"."palabras" VALUES ('could', 'podría', 'poderia', '3', '682', null);
INSERT INTO "public"."palabras" VALUES ('count', 'cuenta', 'contagem', '3', '683', null);
INSERT INTO "public"."palabras" VALUES ('cover', 'cubrir', 'cobrir', '3', '684', null);
INSERT INTO "public"."palabras" VALUES ('crowd', 'multitud', 'multidão', '3', '685', null);
INSERT INTO "public"."palabras" VALUES ('cry', 'llorar', 'chorar', '3', '686', null);
INSERT INTO "public"."palabras" VALUES ('cup', 'taza', 'copo', '3', '687', null);
INSERT INTO "public"."palabras" VALUES ('dare', 'atrevimiento', 'ousar', '3', '688', null);
INSERT INTO "public"."palabras" VALUES ('daughter', 'hija', 'filha', '3', '689', null);
INSERT INTO "public"."palabras" VALUES ('day', 'día', 'dia', '3', '690', 'http://i.giphy.com/7ZwSQb7XsEYE0.gif');
INSERT INTO "public"."palabras" VALUES ('deal', 'acuerdo', 'acordo', '3', '691', null);
INSERT INTO "public"."palabras" VALUES ('dear', 'querido', 'caro', '3', '692', null);
INSERT INTO "public"."palabras" VALUES ('deep', 'profundo', 'profundo', '3', '693', null);
INSERT INTO "public"."palabras" VALUES ('rear', 'posterior', 'traseiro', '3', '694', null);
INSERT INTO "public"."palabras" VALUES ('real', 'real', 'real', '3', '695', null);
INSERT INTO "public"."palabras" VALUES ('receive', 'recibir', 'receber', '3', '696', null);
INSERT INTO "public"."palabras" VALUES ('remain', 'permanecer', 'permanecer', '3', '697', null);
INSERT INTO "public"."palabras" VALUES ('reply', 'replicar', 'resposta', '3', '698', null);
INSERT INTO "public"."palabras" VALUES ('noise', 'ruido', 'barulho', '3', '699', null);
INSERT INTO "public"."palabras" VALUES ('north', 'norte', 'norte', '3', '700', 'http://i.giphy.com/26tPcgtbhhbU88U2A.gif');
INSERT INTO "public"."palabras" VALUES ('nothing', 'nada', 'nada', '3', '701', null);
INSERT INTO "public"."palabras" VALUES ('of', 'de', 'do', '3', '702', null);
INSERT INTO "public"."palabras" VALUES ('often', 'a menudo', 'frequentemente', '3', '703', null);
INSERT INTO "public"."palabras" VALUES ('office', 'oficina', 'escritório', '3', '704', null);
INSERT INTO "public"."palabras" VALUES ('oh', 'oh', 'ó', '3', '705', null);
INSERT INTO "public"."palabras" VALUES ('only', 'solamente', 'só', '3', '706', null);
INSERT INTO "public"."palabras" VALUES ('order', 'orden', 'ordem', '3', '707', null);
INSERT INTO "public"."palabras" VALUES ('own', 'propio', 'próprio', '3', '708', null);
INSERT INTO "public"."palabras" VALUES ('people', 'gente', 'pessoas', '3', '709', null);
INSERT INTO "public"."palabras" VALUES ('perfect', 'perfecto', 'perfeito', '3', '710', 'http://i.giphy.com/xo6QL3gjGMimA.gif');
INSERT INTO "public"."palabras" VALUES ('picture', 'imagen', 'figura', '3', '711', null);
INSERT INTO "public"."palabras" VALUES ('place', 'lugar', 'lugar', '3', '712', null);
INSERT INTO "public"."palabras" VALUES ('possible', 'posible', 'possível', '3', '713', null);
INSERT INTO "public"."palabras" VALUES ('prepare', 'preparar', 'preparar', '3', '714', null);
INSERT INTO "public"."palabras" VALUES ('press', 'prensa', 'pressione', '3', '715', null);
INSERT INTO "public"."palabras" VALUES ('price', 'precio', 'preço', '3', '716', null);
INSERT INTO "public"."palabras" VALUES ('produce', 'producir', 'produzir', '3', '717', null);
INSERT INTO "public"."palabras" VALUES ('prove', 'probar', 'provar', '3', '718', null);
INSERT INTO "public"."palabras" VALUES ('pure', 'puro', 'puro', '3', '719', null);
INSERT INTO "public"."palabras" VALUES ('purpose', 'propósito', 'propósito', '3', '720', 'http://i.giphy.com/d4blihcFNkwE3fEI.gif');
INSERT INTO "public"."palabras" VALUES ('quarter', 'trimestre', 'trimestre', '3', '721', null);
INSERT INTO "public"."palabras" VALUES ('question', 'pregunta', 'pergunta', '3', '722', null);
INSERT INTO "public"."palabras" VALUES ('race', 'raza', 'corrida', '3', '723', null);
INSERT INTO "public"."palabras" VALUES ('read', 'leer', 'ler', '3', '724', null);
INSERT INTO "public"."palabras" VALUES ('real', 'real', 'real', '3', '725', null);
INSERT INTO "public"."palabras" VALUES ('realize', 'realizar', 'perceber', '3', '726', null);
INSERT INTO "public"."palabras" VALUES ('reason', 'razón', 'razão', '3', '727', null);
INSERT INTO "public"."palabras" VALUES ('red', 'rojo', 'vermelho', '3', '728', null);
INSERT INTO "public"."palabras" VALUES ('rest', 'descanso', 'descansar', '3', '729', null);
INSERT INTO "public"."palabras" VALUES ('right', 'bien', 'certo', '3', '730', 'http://i.giphy.com/l0HlSH2gsSrxJySnS.gif');
INSERT INTO "public"."palabras" VALUES ('ring', 'anillo', 'anel', '3', '731', null);
INSERT INTO "public"."palabras" VALUES ('river', 'rio', 'rio', '3', '732', null);
INSERT INTO "public"."palabras" VALUES ('rose', 'rosa', 'rosa', '3', '733', null);
INSERT INTO "public"."palabras" VALUES ('rule', 'regla', 'regra', '3', '734', null);
INSERT INTO "public"."palabras" VALUES ('salt', 'sal', 'sal', '3', '735', null);
INSERT INTO "public"."palabras" VALUES ('sell', 'vender', 'vender', '3', '736', null);
INSERT INTO "public"."palabras" VALUES ('serve', 'servir', 'servir', '3', '737', null);
INSERT INTO "public"."palabras" VALUES ('seven', 'siete', 'sete', '3', '738', null);
INSERT INTO "public"."palabras" VALUES ('share', 'distribuir', 'compartilhar', '3', '739', null);
INSERT INTO "public"."palabras" VALUES ('she', 'ella', 'ela', '3', '740', 'http://i.giphy.com/XB6pGqvOfJqY8.gif');
INSERT INTO "public"."palabras" VALUES ('south', 'sur', 'sul', '3', '741', null);
INSERT INTO "public"."palabras" VALUES ('spring', 'primavera', 'primavera', '3', '742', null);
INSERT INTO "public"."palabras" VALUES ('square', 'cuadro', 'quadrado', '3', '743', null);
INSERT INTO "public"."palabras" VALUES ('stock', 'surtir, abastecer', 'estoque', '3', '744', null);
INSERT INTO "public"."palabras" VALUES ('strange', 'extraño', 'estranho', '3', '745', null);
INSERT INTO "public"."palabras" VALUES ('street', 'calle', 'rua', '3', '746', null);
INSERT INTO "public"."palabras" VALUES ('strong', 'fuerte', 'forte', '3', '747', null);
INSERT INTO "public"."palabras" VALUES ('subject', 'sujeto', 'sujeito', '3', '748', null);
INSERT INTO "public"."palabras" VALUES ('success', 'éxito', 'sucesso', '3', '749', null);
INSERT INTO "public"."palabras" VALUES ('suffer', 'sufrir', 'sofrer', '3', '750', 'http://i.giphy.com/WwwgLxGCz4gTu.gif');
INSERT INTO "public"."palabras" VALUES ('sugar', 'azúcar', 'açúcar', '3', '751', null);
INSERT INTO "public"."palabras" VALUES ('summer', 'verano', 'verão', '3', '752', null);
INSERT INTO "public"."palabras" VALUES ('sun', 'sol', 'sol', '3', '753', null);
INSERT INTO "public"."palabras" VALUES ('supply', 'suplir', 'fornecem', '3', '754', null);
INSERT INTO "public"."palabras" VALUES ('suppose', 'suponer', 'supor', '3', '755', null);
INSERT INTO "public"."palabras" VALUES ('surprise', 'sorpresa', 'surpresa', '3', '756', null);
INSERT INTO "public"."palabras" VALUES ('sweet', 'dulce', 'doce', '3', '757', null);
INSERT INTO "public"."palabras" VALUES ('table', 'mesa', 'mesa', '3', '758', null);
INSERT INTO "public"."palabras" VALUES ('teach', 'enseñar', 'ensinar', '3', '759', null);
INSERT INTO "public"."palabras" VALUES ('thank', 'agradecer', 'obrigado', '3', '760', 'http://i.giphy.com/4XEGfMYZMnm0.gif');
INSERT INTO "public"."palabras" VALUES ('that', 'ese', 'aquele', '3', '761', null);
INSERT INTO "public"."palabras" VALUES ('the', 'el, la', 'a, o', '3', '762', null);
INSERT INTO "public"."palabras" VALUES ('their', 'su, suya, ellos', 'seus, deles, delas', '3', '763', null);
INSERT INTO "public"."palabras" VALUES ('then', 'entonces', 'então', '3', '764', null);
INSERT INTO "public"."palabras" VALUES ('there', 'allá', 'há', '3', '765', null);
INSERT INTO "public"."palabras" VALUES ('these', 'estos', 'estes', '3', '766', null);
INSERT INTO "public"."palabras" VALUES ('they', 'ellos', 'eles', '3', '767', null);
INSERT INTO "public"."palabras" VALUES ('thing', 'cosa', 'coisa', '3', '768', null);
INSERT INTO "public"."palabras" VALUES ('think', 'pensar', 'pensar', '3', '769', null);
INSERT INTO "public"."palabras" VALUES ('third', 'tercero', 'terceiro', '3', '770', 'http://i.giphy.com/3oz8xw1LEMYw9LuVtS.gif');
INSERT INTO "public"."palabras" VALUES ('this', 'esto', 'esta', '3', '771', null);
INSERT INTO "public"."palabras" VALUES ('those', 'esos', 'Essa', '3', '772', null);
INSERT INTO "public"."palabras" VALUES ('thousand', 'mil', 'mil', '3', '773', null);
INSERT INTO "public"."palabras" VALUES ('three', 'tres', 'três', '3', '774', null);
INSERT INTO "public"."palabras" VALUES ('time', 'tiempo', 'tempo', '3', '775', null);
INSERT INTO "public"."palabras" VALUES ('to', 'a', 'para', '3', '776', null);
INSERT INTO "public"."palabras" VALUES ('told', 'dijo', 'contou', '3', '777', null);
INSERT INTO "public"."palabras" VALUES ('tomorrow', 'mañana', 'amanhã', '3', '778', null);
INSERT INTO "public"."palabras" VALUES ('travel', 'viaje', 'viagem', '3', '779', null);
INSERT INTO "public"."palabras" VALUES ('tree', 'árbol', 'árvore', '3', '780', 'http://i.giphy.com/26BRxBeok96wnAwpy.gif');
INSERT INTO "public"."palabras" VALUES ('trip', 'viaje', 'viagem', '3', '781', null);
INSERT INTO "public"."palabras" VALUES ('trouble', 'problema', 'problema', '3', '782', null);
INSERT INTO "public"."palabras" VALUES ('twelve', 'doce', 'doze', '3', '783', null);
INSERT INTO "public"."palabras" VALUES ('twenty', 'veinte', 'vinte', '3', '784', null);
INSERT INTO "public"."palabras" VALUES ('two', 'dos', 'dois', '3', '785', null);
INSERT INTO "public"."palabras" VALUES ('require', 'requerir', 'Requere', '3', '786', null);
INSERT INTO "public"."palabras" VALUES ('return', 'retornar', 'Retorna', '3', '787', null);
INSERT INTO "public"."palabras" VALUES ('rich', 'rico', 'rico', '3', '788', null);
INSERT INTO "public"."palabras" VALUES ('ride', 'paseo', 'passeio', '3', '789', null);
INSERT INTO "public"."palabras" VALUES ('rock', 'roca', 'Rocha', '3', '790', 'http://i.giphy.com/Fc6pf86FKCeA.gif');
INSERT INTO "public"."palabras" VALUES ('roll', 'rollo', 'rolo', '3', '791', null);
INSERT INTO "public"."palabras" VALUES ('round', 'redondo', 'volta', '3', '792', null);
INSERT INTO "public"."palabras" VALUES ('row', 'fila', 'fila', '3', '793', null);
INSERT INTO "public"."palabras" VALUES ('run', 'correr', 'corre', '3', '794', null);
INSERT INTO "public"."palabras" VALUES ('rush', 'apurarse', 'pressa', '3', '795', null);
INSERT INTO "public"."palabras" VALUES ('sad', 'triste', 'triste', '3', '796', null);
INSERT INTO "public"."palabras" VALUES ('sail', 'navegar', 'navegar', '3', '797', null);
INSERT INTO "public"."palabras" VALUES ('same', 'mismo', 'mesmo', '3', '798', null);
INSERT INTO "public"."palabras" VALUES ('sat', 'sentado', 'Sentou', '3', '799', null);
INSERT INTO "public"."palabras" VALUES ('save', 'guardar', 'salvar', '3', '800', 'http://i.giphy.com/3oz8xDLuiN1GcDA3xC.gif');
INSERT INTO "public"."palabras" VALUES ('saw', 'sierra', 'Serra', '3', '801', null);
INSERT INTO "public"."palabras" VALUES ('say', 'decir', 'dizer', '3', '802', null);
INSERT INTO "public"."palabras" VALUES ('sea', 'océano', 'oceano', '3', '803', null);
INSERT INTO "public"."palabras" VALUES ('season', 'temporada', 'estação', '3', '804', null);
INSERT INTO "public"."palabras" VALUES ('seat', 'asiento', 'assento', '3', '805', null);
INSERT INTO "public"."palabras" VALUES ('see', 'ver', 'Vejo', '3', '806', null);
INSERT INTO "public"."palabras" VALUES ('seed', 'semilla', 'semente', '3', '807', null);
INSERT INTO "public"."palabras" VALUES ('seek', 'buscar', 'procurar', '3', '808', null);
INSERT INTO "public"."palabras" VALUES ('seem', 'parecer', 'parecer', '3', '809', null);
INSERT INTO "public"."palabras" VALUES ('seen', 'viendo', 'visto', '3', '810', 'http://i.giphy.com/b09xElu8in7Lq.gif');
INSERT INTO "public"."palabras" VALUES ('seek', 'buscar', 'procurar', '3', '811', null);
INSERT INTO "public"."palabras" VALUES ('seem', 'parecer', 'parecer', '3', '812', null);
INSERT INTO "public"."palabras" VALUES ('self', 'sí mismo', 'auto', '3', '813', null);
INSERT INTO "public"."palabras" VALUES ('send', 'enviar', 'enviar', '3', '814', null);
INSERT INTO "public"."palabras" VALUES ('sent', 'enviado', 'enviei', '3', '815', null);
INSERT INTO "public"."palabras" VALUES ('set', 'conjunto', 'conjunto', '3', '816', null);
INSERT INTO "public"."palabras" VALUES ('settle', 'establecer', 'resolver', '3', '817', null);
INSERT INTO "public"."palabras" VALUES ('several', 'varios', 'de várias', '3', '818', null);
INSERT INTO "public"."palabras" VALUES ('shade', 'sombra', 'sombra', '3', '819', null);
INSERT INTO "public"."palabras" VALUES ('shake', 'batir', 'agitar', '3', '820', 'http://i.giphy.com/JvtrhAX8aXo4w.gif');
INSERT INTO "public"."palabras" VALUES ('shall', 'deberá', 'deve', '3', '821', null);
INSERT INTO "public"."palabras" VALUES ('shape', 'figura', 'forma', '3', '822', null);
INSERT INTO "public"."palabras" VALUES ('shine', 'brillo', 'brilho', '3', '823', null);
INSERT INTO "public"."palabras" VALUES ('ship', 'barco', 'navio', '3', '824', null);
INSERT INTO "public"."palabras" VALUES ('shirt', 'camisa', 'camisa', '3', '825', null);
INSERT INTO "public"."palabras" VALUES ('shop', 'almacén', 'loja', '3', '826', null);
INSERT INTO "public"."palabras" VALUES ('shore', 'costa', 'costa', '3', '827', null);
INSERT INTO "public"."palabras" VALUES ('short', 'corto', 'baixo', '3', '828', null);
INSERT INTO "public"."palabras" VALUES ('shot', 'disparo', 'tiro', '3', '829', null);
INSERT INTO "public"."palabras" VALUES ('should', 'debería', 'devemos', '3', '830', 'http://i.giphy.com/ZHn4xJj0hLZ0Q.gif');
INSERT INTO "public"."palabras" VALUES ('shoulder', 'hombro', 'ombro', '3', '831', null);
INSERT INTO "public"."palabras" VALUES ('shout', 'gritar', 'gritar', '3', '832', null);
INSERT INTO "public"."palabras" VALUES ('show', 'mostrar', 'exposição', '3', '833', null);
INSERT INTO "public"."palabras" VALUES ('sick', 'enfermo', 'doente', '3', '834', null);
INSERT INTO "public"."palabras" VALUES ('side', 'lado', 'lado', '3', '835', null);
INSERT INTO "public"."palabras" VALUES ('sight', 'vista', 'vista', '3', '836', null);
INSERT INTO "public"."palabras" VALUES ('sign', 'firma, aviso', 'assinar, sinal', '3', '837', null);
INSERT INTO "public"."palabras" VALUES ('silver', 'plata', 'prata', '3', '838', null);
INSERT INTO "public"."palabras" VALUES ('since', 'desde', 'desde', '3', '839', null);
INSERT INTO "public"."palabras" VALUES ('single', 'soltero, solo', 'solteiro, só', '3', '840', 'http://i.giphy.com/n9hFY6sdZ0HWo.gif');
INSERT INTO "public"."palabras" VALUES ('sit', 'sentarse', 'sentar', '3', '841', null);
INSERT INTO "public"."palabras" VALUES ('six', 'seis', 'seis', '3', '842', null);
INSERT INTO "public"."palabras" VALUES ('skin', 'piel', 'pele', '3', '843', null);
INSERT INTO "public"."palabras" VALUES ('sky', 'cielo', 'céu', '3', '844', null);
INSERT INTO "public"."palabras" VALUES ('sleep', 'dormir', 'dormir', '3', '845', null);
INSERT INTO "public"."palabras" VALUES ('slow', 'despacio', 'lento', '3', '846', null);
INSERT INTO "public"."palabras" VALUES ('small', 'pequeño', 'pequeno', '3', '847', null);
INSERT INTO "public"."palabras" VALUES ('smile', 'sonreír', 'sorrir', '3', '848', null);
INSERT INTO "public"."palabras" VALUES ('smoke', 'fumar, humo', 'fumaça', '3', '849', null);
INSERT INTO "public"."palabras" VALUES ('snow', 'nieve', 'neve', '3', '850', 'http://i.giphy.com/zEJRrMkDvRe5G.gif');
INSERT INTO "public"."palabras" VALUES ('so', 'así', 'assim', '3', '851', null);
INSERT INTO "public"."palabras" VALUES ('soft', 'suave', 'suave', '3', '852', null);
INSERT INTO "public"."palabras" VALUES ('soil', 'suelo, tierra', 'solo', '3', '853', null);
INSERT INTO "public"."palabras" VALUES ('sold', 'vendido', 'vendido', '3', '854', null);
INSERT INTO "public"."palabras" VALUES ('some', 'alguno', 'alguns', '3', '855', null);
INSERT INTO "public"."palabras" VALUES ('song', 'canción', 'canção', '3', '856', null);
INSERT INTO "public"."palabras" VALUES ('soon', 'pronto', 'logo', '3', '857', null);
INSERT INTO "public"."palabras" VALUES ('sorry', 'lo siento', 'desculpa', '3', '858', null);
INSERT INTO "public"."palabras" VALUES ('sort', 'ordenar', 'ordenar', '3', '859', null);
INSERT INTO "public"."palabras" VALUES ('soul', 'alma', 'alma', '3', '860', 'http://i.giphy.com/3o7TKxJRKk8uPOOdgY.gif');
INSERT INTO "public"."palabras" VALUES ('sound', 'sonido', 'som', '3', '861', null);
INSERT INTO "public"."palabras" VALUES ('speak', 'hablar', 'falar', '3', '862', null);
INSERT INTO "public"."palabras" VALUES ('spend', 'gastar', 'gastar', '3', '863', null);
INSERT INTO "public"."palabras" VALUES ('spoke', 'habló', 'falou', '3', '864', null);
INSERT INTO "public"."palabras" VALUES ('spot', 'lugar, punto', 'local', '3', '865', null);
INSERT INTO "public"."palabras" VALUES ('spread', 'esparcir', 'espalhar', '3', '866', null);
INSERT INTO "public"."palabras" VALUES ('stand', 'de pie', 'ficar de pé', '3', '867', null);
INSERT INTO "public"."palabras" VALUES ('star', 'estrella', 'estrela', '3', '868', null);
INSERT INTO "public"."palabras" VALUES ('start', 'empezar', 'começar', '3', '869', null);
INSERT INTO "public"."palabras" VALUES ('stay', 'permanecer', 'fique', '3', '870', 'http://i.giphy.com/L6HdwO0IhAxkQ.gif');
INSERT INTO "public"."palabras" VALUES ('step', 'paso', 'passo', '3', '871', null);
INSERT INTO "public"."palabras" VALUES ('stick', 'palo, pegar', 'Vara', '3', '872', null);
INSERT INTO "public"."palabras" VALUES ('still', 'todavía', 'ainda', '3', '873', null);
INSERT INTO "public"."palabras" VALUES ('stood', 'estar, destacado', 'ficou', '3', '874', null);
INSERT INTO "public"."palabras" VALUES ('stone', 'piedra', 'pedra', '3', '875', null);
INSERT INTO "public"."palabras" VALUES ('store', 'tienda, almacenar', 'loja', '3', '876', null);
INSERT INTO "public"."palabras" VALUES ('storm', 'tormenta', 'tempestade', '3', '877', null);
INSERT INTO "public"."palabras" VALUES ('straight', 'derecho', 'direto', '3', '878', null);
INSERT INTO "public"."palabras" VALUES ('stream', 'corriente', 'corrente', '3', '879', null);
INSERT INTO "public"."palabras" VALUES ('strength', 'fuerza', 'força', '3', '880', 'http://i.giphy.com/OqEBxidnkAut2.gif');
INSERT INTO "public"."palabras" VALUES ('strike', 'golpe, huelga', 'greve', '3', '881', null);
INSERT INTO "public"."palabras" VALUES ('study', 'estudiar', 'estude', '3', '882', null);
INSERT INTO "public"."palabras" VALUES ('such', 'de esa clase', 'tal', '3', '883', null);
INSERT INTO "public"."palabras" VALUES ('sudden', 'repentino', 'de repente', '3', '884', null);
INSERT INTO "public"."palabras" VALUES ('suit', 'vestido, apartamento', 'terno', '3', '885', null);
INSERT INTO "public"."palabras" VALUES ('tail', 'cola', 'rabo', '3', '886', null);
INSERT INTO "public"."palabras" VALUES ('take', 'tomar', 'levar', '3', '887', null);
INSERT INTO "public"."palabras" VALUES ('taken', 'tomado', 'tomado', '3', '888', null);
INSERT INTO "public"."palabras" VALUES ('talk', 'hablar', 'conversa', '3', '889', null);
INSERT INTO "public"."palabras" VALUES ('tall', 'alto', 'alto', '3', '890', 'http://i.giphy.com/11Feog5PTumNnq.gif');
INSERT INTO "public"."palabras" VALUES ('taste', 'gustar', 'gosto', '3', '891', null);
INSERT INTO "public"."palabras" VALUES ('tear', 'lagrima, rasgar', 'lágrima', '3', '892', null);
INSERT INTO "public"."palabras" VALUES ('tell', 'decir', 'contar', '3', '893', null);
INSERT INTO "public"."palabras" VALUES ('ten', 'diez', 'dez', '3', '894', null);
INSERT INTO "public"."palabras" VALUES ('than', 'mas que', 'do que', '3', '895', null);
INSERT INTO "public"."palabras" VALUES ('then', 'entonces', 'então', '3', '896', null);
INSERT INTO "public"."palabras" VALUES ('therefore', 'por lo tanto', 'portanto', '3', '897', null);
INSERT INTO "public"."palabras" VALUES ('thick', 'grueso', 'Grosso', '3', '898', null);
INSERT INTO "public"."palabras" VALUES ('thin', 'delgado', 'fino', '3', '899', null);
INSERT INTO "public"."palabras" VALUES ('though', 'aunque', 'embora', '3', '900', 'http://i.giphy.com/4rmeEoEGVh4BO.gif');
INSERT INTO "public"."palabras" VALUES ('thought', 'pensamiento', 'pensamento', '3', '901', null);
INSERT INTO "public"."palabras" VALUES ('threw', 'arrojó, lanzar', 'lançar, jogou', '3', '902', null);
INSERT INTO "public"."palabras" VALUES ('through', 'mediante', 'através', '3', '903', null);
INSERT INTO "public"."palabras" VALUES ('throw', 'lanzar', 'lançar', '3', '904', null);
INSERT INTO "public"."palabras" VALUES ('tie', 'amarrar, corbata', 'gravata, laço', '3', '905', null);
INSERT INTO "public"."palabras" VALUES ('till', 'hasta', 'até', '3', '906', null);
INSERT INTO "public"."palabras" VALUES ('together', 'juntos', 'juntos', '3', '907', null);
INSERT INTO "public"."palabras" VALUES ('too', 'también', 'também', '3', '908', null);
INSERT INTO "public"."palabras" VALUES ('took', 'tomado', 'tomou', '3', '909', null);
INSERT INTO "public"."palabras" VALUES ('top', 'superior', 'top', '3', '910', 'http://i.giphy.com/6AyHfuvZTttRe.gif');
INSERT INTO "public"."palabras" VALUES ('touch', 'tocar', 'tocar', '3', '911', null);
INSERT INTO "public"."palabras" VALUES ('toward', 'hacia', 'em direção a', '3', '912', null);
INSERT INTO "public"."palabras" VALUES ('town', 'pueblo', 'vila', '3', '913', null);
INSERT INTO "public"."palabras" VALUES ('trade', 'negocio, canje', 'comércio', '3', '914', null);
INSERT INTO "public"."palabras" VALUES ('true', 'cierto', 'verdade', '3', '915', null);
INSERT INTO "public"."palabras" VALUES ('trust', 'confianza', 'Confiar em', '3', '916', null);
INSERT INTO "public"."palabras" VALUES ('try', 'probar', 'experimentar', '3', '917', null);
INSERT INTO "public"."palabras" VALUES ('turn', 'giro', 'vez', '3', '918', null);
INSERT INTO "public"."palabras" VALUES ('until', 'hasta', 'até', '3', '919', null);
INSERT INTO "public"."palabras" VALUES ('up', 'arriba', 'acima', '3', '920', 'http://i.giphy.com/EAM1J0DyGanV6.gif');
INSERT INTO "public"."palabras" VALUES ('upon', 'encima', 'sobre', '3', '921', null);
INSERT INTO "public"."palabras" VALUES ('use', 'uso', 'usar', '3', '922', null);
INSERT INTO "public"."palabras" VALUES ('vary', 'variar', 'variar', '3', '923', null);
INSERT INTO "public"."palabras" VALUES ('very', 'mucho', 'muito', '3', '924', null);
INSERT INTO "public"."palabras" VALUES ('view', 'vista', 'visão', '3', '925', null);
INSERT INTO "public"."palabras" VALUES ('wave', 'ola', 'onda', '3', '926', null);
INSERT INTO "public"."palabras" VALUES ('wear', 'vestir, usar', 'vestem', '3', '927', null);
INSERT INTO "public"."palabras" VALUES ('weather', 'clima', 'clima', '3', '928', null);
INSERT INTO "public"."palabras" VALUES ('week', 'semana', 'semana', '3', '929', null);
INSERT INTO "public"."palabras" VALUES ('weak', 'débil', 'fraco', '3', '930', 'http://i.giphy.com/l0HFiOtai3t3xIoLK.gif');
INSERT INTO "public"."palabras" VALUES ('went', 'fuimos', 'foi', '3', '931', null);
INSERT INTO "public"."palabras" VALUES ('when', 'cuando', 'quando', '3', '932', null);
INSERT INTO "public"."palabras" VALUES ('whether', 'aunque de escoger', 'se', '3', '933', null);
INSERT INTO "public"."palabras" VALUES ('while', 'mientras', 'enquanto', '3', '934', null);
INSERT INTO "public"."palabras" VALUES ('whole', 'entero', 'todo', '3', '935', null);
INSERT INTO "public"."palabras" VALUES ('whom', 'a quien', 'quem', '3', '936', null);
INSERT INTO "public"."palabras" VALUES ('wide', 'ancho', 'largo', '3', '937', null);
INSERT INTO "public"."palabras" VALUES ('wild', 'salvaje', 'selvagem', '3', '938', null);
INSERT INTO "public"."palabras" VALUES ('wind', 'viento', 'vento', '3', '939', null);
INSERT INTO "public"."palabras" VALUES ('wing', 'ala', 'asa', '3', '940', 'http://i.giphy.com/Eb63LPCiBNwRy.gif');
INSERT INTO "public"."palabras" VALUES ('wish', 'deseo', 'desejo', '3', '941', null);
INSERT INTO "public"."palabras" VALUES ('within', 'dentro de', 'dentro', '3', '942', null);
INSERT INTO "public"."palabras" VALUES ('without', 'sin, fuera de', 'sem', '3', '943', null);
INSERT INTO "public"."palabras" VALUES ('wonder', 'asombro', 'maravilha', '3', '944', null);
INSERT INTO "public"."palabras" VALUES ('won''t', 'no lo hará', 'não vai', '3', '945', null);
INSERT INTO "public"."palabras" VALUES ('worth', 'valor', 'valor', '3', '946', null);
INSERT INTO "public"."palabras" VALUES ('would', 'haría', 'seria', '3', '947', null);
INSERT INTO "public"."palabras" VALUES ('yard', 'partió, yarda', 'jarda, quintal', '3', '948', null);
INSERT INTO "public"."palabras" VALUES ('yet', 'todavía', 'ainda', '3', '949', null);
INSERT INTO "public"."palabras" VALUES (null, '
""
', null, null, '950', 'http://i.giphy.com/1iTH1WIUjM0VATSw.gif');

-- ----------------------------
-- Alter Sequences Owned By 
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table palabras
-- ----------------------------
ALTER TABLE "public"."palabras" ADD PRIMARY KEY ("id");
